Repository zimmerman-team/Dx.client, pull requests merged in 2023-05, with the labels that each got.

#6 Feat/statistical table
  src/app/components/Select/selectWithIcon.tsx
  src/app/components/Select/simpleSelect.tsx
  src/app/components/Table/Preview-table/StatisticalRepresentations.tsx
  src/app/components/Table/Preview-table/StatisticalTableToolBox/index.tsx
  src/app/components/Table/Preview-table/StatisticalTableToolBox/style.ts
  src/app/components/Table/Preview-table/data.ts
  src/app/components/Table/Preview-table/index.tsx
  src/app/components/Table/Preview-table/statisticDisplay.tsx
  src/app/components/Table/Preview-table/style.ts
  src/app/fragments/datasets-fragment/assets/clock-icon.svg
  src/app/fragments/datasets-fragment/assets/close-icon.svg
  src/app/fragments/datasets-fragment/assets/sort.svg
  src/app/fragments/datasets-fragment/component/data-table/index.tsx
  src/app/fragments/datasets-fragment/component/dataParserToolBox/dataParsingOptions.tsx
  src/app/fragments/datasets-fragment/component/dataParserToolBox/index.tsx
  src/app/fragments/datasets-fragment/upload-steps/finishedFragment.tsx
  src/app/fragments/datasets-fragment/upload-steps/index.tsx
  src/app/fragments/datasets-fragment/upload-steps/previewFragment.tsx
  src/app/hooks/useChartsRawData.tsx
  src/app/hooks/useDataThemesEchart.tsx
  src/app/modules/chart-module/components/toolbox/views/steps/panels-content/SelectDataset.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/modules/chart-module/routes/preview/index.tsx
  src/app/modules/data-themes-module/components/data-table/data.tsx
  src/app/modules/data-themes-module/components/data-table/index.tsx
  src/app/modules/data-themes-module/sub-modules/theme-builder/views/common/styles.ts
  src/app/modules/data-themes-module/sub-modules/theme-builder/views/preview/index.tsx
  src/app/modules/home-module/components/Datasets/datasetsGrid.tsx
Labels: size/XXL

#7 feat: dataset upload drag and drop implementation
  package.json
  src/app/fragments/datasets-fragment/style.ts
  src/app/fragments/datasets-fragment/upload-steps/addDatasetFragment.tsx
  src/app/fragments/datasets-fragment/upload-steps/index.tsx
  src/app/utils/formatBytes.ts
  yarn.lock
Labels: size/L

#9 feat: added port definition to craco config
  README.md
  craco.config.js
Labels: size/XS

#11 fix: adjust RH panel handle position
  src/app/modules/report-module/components/right-panel/index.tsx
Labels: size/XS

#12 fix: make RH panel customize scrollbar not visible
  src/app/modules/chart-module/components/toolbox/views/steps/index.tsx
  src/app/modules/chart-module/components/toolbox/views/steps/panels-content/Customize.tsx
Labels: size/S
