Repository zimmerman-team/Dx.client, pull requests merged in 2023-11, with the labels that each got.

#52 Feat/dx 735
  src/app/modules/home-module/assets/communicate.svg
  src/app/modules/home-module/assets/connect-data.svg
  src/app/modules/home-module/assets/convert.svg
  src/app/modules/home-module/assets/whydx-ellipses.svg
  src/app/modules/home-module/assets/whydx-search-illustration.svg
  src/app/modules/home-module/components/Footer/index.tsx
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/home-module/sub-modules/partners/components/empowerBlock.tsx
  src/app/modules/home-module/sub-modules/partners/style.ts
  src/app/modules/home-module/sub-modules/why-dx/components/benefitsBlock.tsx
  src/app/modules/home-module/sub-modules/why-dx/components/keyFeaturesBlock.tsx
  src/app/modules/home-module/sub-modules/why-dx/components/simpleStepsBlock.tsx
  src/app/modules/home-module/sub-modules/why-dx/components/tryUsBlock.tsx
  src/app/modules/home-module/sub-modules/why-dx/index.tsx
  src/app/modules/home-module/sub-modules/why-dx/style.ts
Labels: size/XXL

#50 Fix/bnc fix
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/mapping/data.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  yarn.lock
Labels: size/M

#53 Feat/visual updates
  public/index.html
  src/app/components/AppBar/index.tsx
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/modules/common/subheader-toolbar/SubheaderToolbar.tsx
  src/app/modules/common/subheader-toolbar/data.ts
  src/app/modules/home-module/assets/about-dx.svg
  src/app/modules/home-module/assets/about-ellipses.svg
  src/app/modules/home-module/assets/about-mission.svg
  src/app/modules/home-module/components/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/Footer/asset/logo.svg
  src/app/modules/home-module/components/Footer/index.tsx
  src/app/modules/home-module/components/Footer/style.ts
  src/app/modules/home-module/sub-modules/about/components/teamBlock.tsx
  src/app/modules/home-module/sub-modules/about/index.tsx
  src/app/modules/home-module/sub-modules/about/style.ts
  src/app/modules/home-module/sub-modules/partners/components/empowerBlock.tsx
  src/app/modules/report-module/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowFrame.tsx
  src/app/modules/report-module/views/create/index.tsx
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
Labels: size/XXL

#54 Feat/gen updates
  src/app/Routes.tsx
  src/app/components/AppBar/index.tsx
  src/app/modules/common/newsletterForm/index.tsx
  src/app/modules/home-module/assets/linkedIn-icon.svg
  src/app/modules/home-module/components/Footer/index.tsx
  src/app/modules/home-module/sub-modules/about/components/teamBlock.tsx
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/report-module/views/ai-template/index.tsx
Labels: size/L

#55 Feat/partners page
  package.json
  src/app/fragments/datasets-fragment/upload-steps/finishedFragment.tsx
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/home-module/sub-modules/partners/components/bestDecisionBlock.tsx
  src/app/modules/home-module/sub-modules/partners/components/empowerBlock.tsx
  src/app/modules/home-module/sub-modules/partners/components/ourPartnersBlock.tsx
  src/app/modules/home-module/sub-modules/partners/components/useDXBlock.tsx
  src/app/modules/home-module/sub-modules/partners/index.tsx
  src/app/modules/home-module/sub-modules/partners/style.ts
  yarn.lock
Labels: size/L

#56 feat: make contact us form function
  src/app/modules/home-module/sub-modules/contact/index.tsx
Labels: size/M

#58 Fix/bug fixes
  src/app/components/ToolBoxPanel/components/filters/data.ts
  src/app/fragments/datasets-fragment/upload-steps/addDatasetFragment.tsx
  src/app/hooks/useChartsRawData.tsx
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/customize/data.ts
  src/app/modules/chart-module/routes/customize/index.tsx
  src/app/modules/chart-module/routes/data/index.tsx
  src/app/modules/chart-module/routes/export/data.ts
  src/app/modules/chart-module/routes/export/index.tsx
  src/app/modules/chart-module/routes/filters/components/ExpandedFilterGroup.tsx
  src/app/modules/chart-module/routes/filters/data.ts
  src/app/modules/chart-module/routes/filters/index.tsx
  src/app/modules/chart-module/routes/lock/data.ts
  src/app/modules/chart-module/routes/lock/index.tsx
  src/app/modules/chart-module/routes/mapping/data.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/chart-module/routes/text/RichEditor/buttons.tsx
  src/app/modules/common/subheader-toolbar/SubheaderToolbar.tsx
  src/app/modules/common/subheader-toolbar/index.tsx
  src/app/modules/data-themes-module/sub-modules/theme-builder/views/mapping/index.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  src/app/modules/report-module/index.tsx
  src/app/state/api/index.ts
  src/app/state/api/interfaces/index.ts
Labels: size/XL

#57 DX-843
  src/app/Routes.tsx
  src/app/components/Dialogs/logOutDialog.tsx
  src/app/fragments/datasets-fragment/upload-steps/index.tsx
  src/app/hooks/useChartsRawData.tsx
  src/app/modules/chart-module/components/toolbox/index.tsx
  src/app/modules/chart-module/data.ts
  src/app/modules/chart-module/index.tsx
  src/app/modules/common/subheader-toolbar/SubheaderToolbar.tsx
  src/app/modules/common/subheader-toolbar/index.tsx
  src/app/modules/home-module/components/Charts/chartsGrid.tsx
  src/app/modules/home-module/components/Charts/reformedGridItem.tsx
  src/app/modules/home-module/components/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/Reports/reformedGridItem.tsx
  src/app/modules/home-module/components/Reports/reportsGrid.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/data.ts
  src/app/modules/report-module/index.tsx
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/preview/data.ts
  src/app/modules/report-module/views/preview/index.tsx
  src/app/state/api/action-reducers/sync/index.ts
  src/app/state/api/index.ts
  src/app/state/api/interfaces/index.ts
  src/app/state/store/index.ts
  src/app/utils/RouteWithAppBar.tsx
  yarn.lock
Labels: size/L
