Repository zimmerman-team/Dx.client, pull requests merged in 2023-06, with the labels that each got.

#18 fix: line chart tooltip fix - DX-305
  src/app/hooks/useChartsRawData.tsx
  src/app/hooks/useDataThemesEchart.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
Labels: size/M

#19 Feat/google drive file picker - DX-254
  package.json
  src/app/fragments/datasets-fragment/upload-steps/addDatasetFragment.tsx
  src/app/fragments/datasets-fragment/upload-steps/index.tsx
  yarn.lock
Labels: size/M

#22 feat: add new dataset button set to enabled
  src/app/modules/chart-module/components/toolbox/views/steps/index.tsx
Labels: size/XS

#23 Report container resize & big number chart type
  .vscode/settings.json
  package.json
  src/app/assets/icons/data-themes-chart-types/bigNumber.tsx
  src/app/assets/icons/data-themes-chart-types/coloredBigNumber.tsx
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/data.ts
  src/app/modules/chart-module/routes/chart-type/data.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/home-module/components/Charts/gridItem.tsx
  src/app/modules/home-module/components/Charts/reformedGridItem.tsx
  src/app/modules/home-module/components/Datasets/gridItem.tsx
  src/app/modules/home-module/components/Datasets/reformedGridItem.tsx
  src/app/modules/home-module/components/Reports/reformedGridItem.tsx
  src/app/modules/home-module/components/Table/index.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  src/app/modules/report-module/components/grid-columns/index.tsx
  src/app/modules/report-module/components/order-container/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/data.ts
  src/app/modules/report-module/index.tsx
  src/app/modules/report-module/sub-module/components/headerBlock/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/addRowFrameButton.tsx
  src/app/modules/report-module/sub-module/rowStructure/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowFrame.tsx
  src/app/modules/report-module/views/create/data.ts
  src/app/modules/report-module/views/create/index.tsx
  src/app/modules/report-module/views/edit/data.ts
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
  src/app/state/recoil/atoms/index.ts
  yarn.lock
Labels: size/XXL

#21 Persist report state on preview mode- Feat/dx 329, DX-342, DX-328
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/components/toolbox/index.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/customize/index.tsx
  src/app/modules/common/subheader-toolbar/data.ts
  src/app/modules/common/subheader-toolbar/index.tsx
  src/app/modules/home-module/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/components/right-panel/data.ts
  src/app/modules/report-module/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/addRowFrameButton.tsx
  src/app/modules/report-module/sub-module/rowStructure/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowFrame.tsx
  src/app/modules/report-module/views/create/data.ts
  src/app/modules/report-module/views/create/index.tsx
  src/app/modules/report-module/views/edit/data.ts
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/initial/data.tsx
  src/app/modules/report-module/views/initial/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
  src/app/state/recoil/atoms/index.ts
Labels: size/L

#24 Feat/new report template - DX-306, DX-330
  src/app/modules/common/subheader-toolbar/index.tsx
  src/app/modules/home-module/components/Reports/reformedGridItem.tsx
  src/app/modules/home-module/components/Reports/reportsGrid.tsx
  src/app/modules/home-module/index.tsx
  src/app/modules/report-module/asset/ai-newsletter-big-ellipse.svg
  src/app/modules/report-module/asset/ai-newsletter-btm-green-ellipse.svg
  src/app/modules/report-module/asset/ai-newsletter-md-btm-ellipse.svg
  src/app/modules/report-module/asset/ai-newsletter-sm-purple-ellispe.svg
  src/app/modules/report-module/asset/ai-newsletter-top-ellipse.svg
  src/app/modules/report-module/asset/ai-newsletter.png
  src/app/modules/report-module/asset/ai-newsletter.svg
  src/app/modules/report-module/asset/chart-illustration.svg
  src/app/modules/report-module/asset/dataset-illustration.svg
  src/app/modules/report-module/asset/mail-img.svg
  src/app/modules/report-module/asset/report-illustration.svg
  src/app/modules/report-module/asset/rightArrow.svg
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/components/right-panel/data.ts
  src/app/modules/report-module/index.tsx
  src/app/modules/report-module/views/ai-template/index.tsx
  src/app/modules/report-module/views/ai-template/style.ts
  src/app/modules/report-module/views/initial/data.tsx
  src/app/modules/report-module/views/initial/index.tsx
  src/app/utils/emailValidation.ts
Labels: size/XXL

#25 Feat/error boundary
  package.json
  src/app/Providers.tsx
  src/app/components/ErrorBoundary/index.tsx
  yarn.lock
Labels: size/L
