Repository zimmerman-team/Dx.client, pull requests merged in 2024-10, with the labels that each got.

#242 fix: Duplicating an asset in detail page leads to undefined route
  src/app/modules/chart-module/__test__/chartSubheaderToolbar.test.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/dataset-module/component/datasetSubHeaderToolbar.tsx
  src/app/modules/report-module/__test__/reportSubheaderToolbar.test.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/index.tsx
Labels: size/S

#239 Feat/dx 1710
  cypress/e2e/1-dx/2-datasets.cy.ts
  cypress/e2e/1-dx/3-charts.cy.ts
  cypress/e2e/1-dx/4-reports.cy.ts
  src/app/components/Dialogs/EmbedChartDialog/index.tsx
  src/app/components/Table/Preview-table/index.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/data.ts
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/components/toolbox/index.tsx
  src/app/modules/chart-module/data.ts
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/select-data/index.tsx
  src/app/modules/common/RichEditor/index.tsx
  src/app/modules/common/no-match-page/asset/404.svg
  src/app/modules/common/no-match-page/asset/bg-ellipse.svg
  src/app/modules/common/no-match-page/index.tsx
  src/app/modules/dataset-module/index.tsx
  src/app/modules/home-module/__test__/reportCard.test.tsx
  src/app/modules/home-module/components/AssetCollection/All/assetsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Charts/chartsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Reports/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/Reports/reportsGrid.tsx
  src/app/modules/home-module/components/Table/index.tsx
  src/app/modules/report-module/__test__/headerBlock.test.tsx
  src/app/modules/report-module/__test__/reportSubheaderToolbar.test.tsx
  src/app/modules/report-module/components/headerBlock/index.tsx
  src/app/modules/report-module/components/headerBlock/style.ts
  src/app/modules/report-module/components/placeholder/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/components/right-panel/data.ts
  src/app/modules/report-module/components/rowStructure/addRowFrameButton.tsx
  src/app/modules/report-module/components/rowStructure/index.tsx
  src/app/modules/report-module/components/rowStructure/rowStructureDisplay.tsx
  src/app/modules/report-module/components/rowStructure/style.ts
  src/app/modules/report-module/data.ts
  src/app/modules/report-module/index.tsx
  src/app/modules/report-module/views/create/data.ts
  src/app/modules/report-module/views/create/index.tsx
  src/app/modules/report-module/views/edit/compareStates.ts
  src/app/modules/report-module/views/edit/data.ts
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
  src/app/state/api/action-reducers/user/index.ts
  src/app/state/api/interfaces/index.ts
  src/app/state/recoil/atoms/index.ts
  src/app/state/store/index.ts
  src/app/utils/setMediaQueryForTest 2.ts
Labels: size/XXL

#238 chore: remove unused state in RB
  src/app/modules/report-module/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
  src/app/modules/report-module/views/edit/data.ts
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/initial/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
  src/app/state/recoil/atoms/index.ts
Labels: size/L

#243 Feat/dx 1710
  src/app/modules/report-module/__test__/headerBlock.test.tsx
  src/app/modules/report-module/components/headerBlock/index.tsx
  src/app/modules/report-module/components/headerBlock/style.ts
  src/app/modules/report-module/components/placeholder/index.tsx
  src/app/modules/report-module/components/rowStructure/addRowFrameButton.tsx
  src/app/modules/report-module/components/rowStructure/index.tsx
  src/app/modules/report-module/components/rowStructure/rowStructureDisplay.tsx
  src/app/modules/report-module/components/rowStructure/style.ts
  src/app/modules/report-module/views/create/index.tsx
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
Labels: size/L

#218 feat: DX-1693 - Dataset Listing Name start with Z-A, must be A-Z
  src/app/modules/home-module/components/AssetCollection/Charts/chartsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Reports/reportsGrid.tsx
Labels: size/S

#245 test: update cypress test
  cypress/e2e/1-dx/4-reports.cy.ts
Labels: size/M

#246 Feat/dx 1887/dx 1890
  src/app/components/Table/Preview-table/index.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/report-module/components/rowStructure/index.tsx
  src/app/modules/report-module/components/rowStructure/rowStructureDisplay.tsx
Labels: size/L

#247 Feat/dx 1852/dx 1934
  src/app/modules/dataset-module/routes/upload-module/upload-steps/addDatasetFragment.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/finishedFragment.tsx
Labels: size/L

#254 feat: DX-1831 - Connect OECD data federated search to frontend
  src/app/modules/dataset-module/routes/upload-module/upload-steps/externalSearch.tsx
  src/app/modules/home-module/assets/oecd-logo.svg
  src/app/modules/home-module/components/AssetCollection/Datasets/externalDatasetCard.tsx
Labels: size/S

#253 test: fix failing report test
  cypress/e2e/4-reports.cy.ts
  src/app/modules/report-module/components/rowStructure/rowStructureDisplay.tsx
  src/app/modules/report-module/views/edit/index.tsx
Labels: size/S

#251 feat: DX-1762 - [Network chart] Make node sizes relative to their act…
  src/app/hooks/useDataThemesEchart.tsx
Labels: size/XS

#250 feat: DX-1653 - Change Meta title & description
  public/index.html
Labels: size/XS

#252 feat: DX-1943 - Investigate sorting in loopback - Should be case inse…
  src/app/modules/dataset-module/routes/edit/index.tsx
  src/app/modules/home-module/components/AssetCollection/All/assetsGrid.tsx
Labels: size/S

#257 Feat/dx 1909
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/components/toolbox/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/index.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/report-module/views/edit/index.tsx
  src/app/state/recoil/atoms/index.ts
Labels: size/M

#260 fix: minor changes
  src/app/components/Dialogs/logOutDialog.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/externalSearch.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/home-module/components/Footer/DesktopFooter.tsx
  src/app/modules/home-module/sub-modules/partners/components/bestDecisionBlock.tsx
  src/app/modules/user-profile-module/index.tsx
  src/app/modules/user-profile-module/layout.tsx
Labels: size/L

#258 feat:DX-1853; table view adjustments
  cypress/e2e/3-charts.cy.ts
  src/app/modules/chart-module/routes/chart-type/data.tsx
  src/app/modules/dataset-module/data.ts
  src/app/modules/home-module/__test__/chartCard.test.tsx
  src/app/modules/home-module/components/AssetCollection/All/assetsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/All/data.ts
  src/app/modules/home-module/components/AssetCollection/Charts/chartsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Charts/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/menuItems.tsx
  src/app/modules/home-module/components/AssetCollection/Reports/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/Reports/reportsGrid.tsx
  src/app/modules/home-module/components/Table/index.tsx
  src/app/modules/report-module/data.ts
Labels: size/XL

#259 Feat/dx 1942
  src/app/modules/report-module/components/reportSubHeaderToolbar/staticToolbar.tsx
  src/app/modules/user-profile-module/asset/info-icon.svg
  src/app/modules/user-profile-module/component/icons.tsx
  src/app/modules/user-profile-module/component/table.tsx
  src/app/modules/user-profile-module/layout.tsx
  src/app/modules/user-profile-module/style.ts
  src/app/modules/user-profile-module/sub-module/billing.tsx
  src/app/modules/user-profile-module/sub-module/profile.tsx
  src/app/modules/user-profile-module/sub-module/settings.tsx
Labels: size/XL
