Repository zimmerman-team/Dx.client, pull requests merged in 2024-11, with the labels that each got.

#264 feat: add tooltips to chart step buttons
  src/app/modules/chart-module/components/toolbox/data.tsx
  src/app/modules/chart-module/components/toolbox/steps/navbar/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/navbar/style.ts
Labels: size/M

#263 fix: update wywiwyg logic
  src/app/modules/common/RichEditor/FontSizeController/index.tsx
  src/app/modules/report-module/components/chart-wrapper/useRenderChartFromAPI.ts
  src/app/modules/report-module/components/reportSubHeaderToolbar/staticToolbar.tsx
Labels: size/M

#265 feat: new chart grouping
  src/app/modules/chart-module/routes/chart-type/data.tsx
Labels: size/M

#268 Feat/dx 1633
  src/app/components/ToolBoxPanel/components/filters/data.ts
  src/app/modules/chart-module/routes/filters/components/ExpandedFilterGroup.tsx
  src/app/modules/chart-module/routes/filters/components/FilterGroup.tsx
Labels: size/S

#267 feat:DX-1862/DX-1951; update chart settings
  package.json
  src/app/hooks/useDataThemesEchart.tsx
  yarn.lock
Labels: size/M

#269 Fix/dx 1936
  src/app/components/AppBar/index.tsx
  src/app/components/Mobile/AppBarSearch/index.tsx
  src/app/modules/chart-module/__test__/filter.test.tsx
  src/app/modules/common/no-match-page/index.tsx
  src/app/modules/home-module/components/AssetCollection/All/assetsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Charts/chartsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Reports/reportsGrid.tsx
  src/app/modules/home-module/components/Footer/DesktopFooter.tsx
  src/app/modules/home-module/components/Footer/MobileFooter.tsx
  src/app/modules/home-module/components/Footer/smallFooter.tsx
  src/app/modules/home-module/components/Footer/style.ts
  src/app/modules/home-module/index.tsx
  src/app/modules/home-module/sub-modules/about/index.tsx
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/home-module/sub-modules/dashboard/index.tsx
  src/app/modules/home-module/sub-modules/partners/index.tsx
  src/app/modules/home-module/sub-modules/pricing/index.tsx
  src/app/modules/home-module/sub-modules/why-dx/index.tsx
  src/index.css
Labels: size/XXL
