Repository zimmerman-team/Dx.client, pull requests merged in 2024-01, with the labels that each got.

#66 Feat/dx 970
  src/app/modules/report-module/data.ts
  src/app/modules/report-module/index.tsx
  src/app/modules/report-module/sub-module/components/headerBlock/index.tsx
  src/app/modules/report-module/views/create/data.ts
  src/app/modules/report-module/views/create/index.tsx
  src/app/modules/report-module/views/edit/data.ts
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/initial/data.tsx
  src/app/modules/report-module/views/initial/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
Labels: size/L

#67 feat: DX-694; duplicate dataset
  src/app/modules/home-module/components/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/Datasets/gridItem.tsx
Labels: size/M

#69 feat:DX-541; logic to reset row sizes
  src/app/modules/report-module/sub-module/rowStructure/index.tsx
Labels: size/M

#71 feat:DX-968; visual update for why-dataXplorer page
  src/app/components/AppBar/index.tsx
  src/app/modules/home-module/assets/whydx-ellipses.svg
  src/app/modules/home-module/components/Footer/asset/copy.svg
  src/app/modules/home-module/components/Footer/index.tsx
  src/app/modules/home-module/components/Footer/style.ts
  src/app/modules/home-module/sub-modules/why-dx/components/keyFeaturesBlock.tsx
  src/app/modules/home-module/sub-modules/why-dx/components/tryUsBlock.tsx
  src/app/modules/home-module/sub-modules/why-dx/index.tsx
  src/app/modules/home-module/sub-modules/why-dx/style.ts
Labels: size/L

#70 feat: Updated the new charts icons available for the CB
  src/app/assets/icons/data-themes-chart-types/areastacked.tsx
  src/app/assets/icons/data-themes-chart-types/bubble.tsx
  src/app/assets/icons/data-themes-chart-types/circlepacking.tsx
  src/app/assets/icons/data-themes-chart-types/circulargraph.tsx
  src/app/assets/icons/data-themes-chart-types/coloredAreastacked.tsx
  src/app/assets/icons/data-themes-chart-types/coloredBubbleChart.tsx
  src/app/assets/icons/data-themes-chart-types/coloredCirclepacking.tsx
  src/app/assets/icons/data-themes-chart-types/coloredCirculargraph.tsx
  src/app/assets/icons/data-themes-chart-types/coloredForcegraph.tsx
  src/app/assets/icons/data-themes-chart-types/coloredPie.tsx
  src/app/assets/icons/data-themes-chart-types/coloredSunburst.tsx
  src/app/assets/icons/data-themes-chart-types/forcegraph.tsx
  src/app/assets/icons/data-themes-chart-types/pie.tsx
  src/app/assets/icons/data-themes-chart-types/sunburst.tsx
  src/app/hooks/useDataThemesEchart.tsx
  src/app/modules/chart-module/assets/areastackedPreview.svg
  src/app/modules/chart-module/assets/bubbleChartPreview.svg
  src/app/modules/chart-module/assets/circlepackingPlaceholder.svg
  src/app/modules/chart-module/assets/circlepackingPreview.svg
  src/app/modules/chart-module/assets/circulargraphPlaceholder.svg
  src/app/modules/chart-module/assets/circulargraphPreview.svg
  src/app/modules/chart-module/assets/forcegraphPlaceholder.svg
  src/app/modules/chart-module/assets/forcegraphPreview.svg
  src/app/modules/chart-module/assets/pieChartPlaceholder.svg
  src/app/modules/chart-module/assets/pieChartPreview.svg
  src/app/modules/chart-module/assets/sunburstPlaceholder.svg
  src/app/modules/chart-module/assets/sunburstPreview.svg
  src/app/modules/chart-module/components/placeholder/index.tsx
  src/app/modules/chart-module/routes/chart-type/data.tsx
  src/app/modules/data-themes-module/sub-modules/theme-builder/views/customize/data.ts
Labels: size/XXL

#68 Feat/dx 584
  src/app/fragments/datasets-fragment/upload-steps/addDatasetFragment.tsx
  src/app/hooks/useChartsRawData.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/data.ts
  src/app/modules/chart-module/components/chartSubheaderToolbar/exportButton.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/infoSnackbar.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/styles.ts
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/components/toolbox/data.ts
  src/app/modules/chart-module/components/toolbox/index.tsx
  src/app/modules/chart-module/components/toolbox/views/steps/panels-content/Mapping.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/customize/data.ts
  src/app/modules/chart-module/routes/customize/index.tsx
  src/app/modules/chart-module/routes/export/data.ts
  src/app/modules/chart-module/routes/export/index.tsx
  src/app/modules/chart-module/routes/filters/data.ts
  src/app/modules/chart-module/routes/filters/index.tsx
  src/app/modules/chart-module/routes/lock/data.ts
  src/app/modules/chart-module/routes/lock/index.tsx
  src/app/modules/chart-module/routes/mapping/data.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/modules/dataset-module/component/datasetSubHeaderToolbar.tsx
  src/app/modules/home-module/components/Charts/chartsGrid.tsx
  src/app/modules/home-module/components/Charts/rhpGridItem.tsx
  src/app/modules/home-module/components/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/Reports/reportsGrid.tsx
  src/app/modules/home-module/index.tsx
  src/app/modules/home-module/sub-modules/explore-assets/index.tsx
  src/app/modules/home-module/sub-modules/partners/index.tsx
  src/app/modules/report-module/asset/EditHeaderIcon.tsx
  src/app/modules/report-module/asset/active-chart-icon.svg
  src/app/modules/report-module/asset/active-elements-icon.svg
  src/app/modules/report-module/asset/active-media-icon.svg
  src/app/modules/report-module/asset/chart-icon.svg
  src/app/modules/report-module/asset/dividerIcon.svg
  src/app/modules/report-module/asset/elements-icon.svg
  src/app/modules/report-module/asset/expand-icon.svg
  src/app/modules/report-module/asset/info-icon.svg
  src/app/modules/report-module/asset/media-icon.svg
  src/app/modules/report-module/asset/rowframe-icon.svg
  src/app/modules/report-module/asset/video-icon.svg
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/autoSaveSwitch/style.css
  src/app/modules/report-module/components/reportSubHeaderToolbar/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/data.tsx
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/panelLabel.tsx
  src/app/modules/report-module/components/right-panel-create-view/rhpGridItem.tsx
  src/app/modules/report-module/components/right-panel-create-view/style.ts
  src/app/modules/report-module/components/right-panel/styles.ts
  src/app/modules/report-module/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/index.tsx
  src/app/state/recoil/atoms/index.ts
  src/index.css
Labels: size/XXL

#73 Feat/update more icons and fixes
  src/app/assets/icons/data-themes-chart-types/heatmap.tsx
  src/app/assets/icons/data-themes-chart-types/radar.tsx
  src/app/components/Table/Preview-table/StatisticalRepresentations.tsx
  src/app/hooks/useDataThemesEchart.tsx
  src/app/modules/chart-module/assets/heatmapPreview.svg
  src/app/modules/chart-module/assets/radarChartPlaceholder.svg
  src/app/modules/chart-module/assets/radarChartPreview.svg
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/components/placeholder/index.tsx
  src/app/modules/chart-module/data.ts
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/chart-type/data.tsx
  src/app/modules/chart-module/routes/customize/data.ts
  src/app/modules/chart-module/routes/customize/index.tsx
  src/app/modules/chart-module/routes/filters/data.ts
  src/app/modules/chart-module/routes/filters/index.tsx
  src/app/modules/chart-module/routes/mapping/data.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
Labels: size/L

#74 fix: bug fixes
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/customize/index.tsx
  src/app/modules/chart-module/routes/filters/index.tsx
  src/app/modules/chart-module/routes/preview-theme/data.ts
  src/app/modules/chart-module/routes/preview-theme/index.tsx
Labels: size/M

#75 Filter logic revision & Google drive authentication
  src/app/fragments/datasets-fragment/upload-steps/addDatasetFragment.tsx
  src/app/hooks/useChartsRawData.tsx
  src/app/modules/chart-module/components/toolbox/data.ts
  src/app/modules/chart-module/components/toolbox/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/navbar/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/navbar/style.ts
  src/app/modules/chart-module/components/toolbox/steps/panels-content/ChartType.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/Customize.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/Filters.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/Mapping.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/SelectDataset.tsx
  src/app/modules/chart-module/components/toolbox/steps/sub-header.tsx
  src/app/modules/chart-module/components/toolbox/styles.ts
  src/app/modules/chart-module/components/toolbox/views/steps/panels-content/Export.tsx
  src/app/modules/chart-module/components/toolbox/views/steps/panels-content/Lock.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/chart-module/routes/customize/index.tsx
  src/app/modules/chart-module/routes/filters/components/ExpandedFilterGroup.tsx
  src/app/modules/chart-module/routes/filters/index.tsx
  src/app/modules/chart-module/routes/filters/utils.ts
  src/app/modules/chart-module/routes/lock/data.ts
  src/app/modules/chart-module/routes/lock/index.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/common/RichEditor/BGColorModal/Picker/colors.ts
  src/app/modules/common/RichEditor/BGColorModal/Picker/index.tsx
  src/app/modules/common/RichEditor/BGColorModal/Picker/picker.tsx
  src/app/modules/common/RichEditor/BGColorModal/index.tsx
  src/app/modules/common/RichEditor/ColorModal/Picker/colorPickerStyles.module.css
  src/app/modules/common/RichEditor/ColorModal/Picker/colors.ts
  src/app/modules/common/RichEditor/ColorModal/Picker/index.tsx
  src/app/modules/common/RichEditor/ColorModal/Picker/picker.tsx
  src/app/modules/common/RichEditor/ColorModal/index.tsx
  src/app/modules/common/RichEditor/ColorModal/modalStyles.module.css
  src/app/modules/common/RichEditor/alignmentStyles.module.css
  src/app/modules/common/RichEditor/buttonInvertedStyles.module.css
  src/app/modules/common/RichEditor/buttonStyles.module.css
  src/app/modules/common/RichEditor/buttons.tsx
  src/app/modules/common/RichEditor/decorators/index.tsx
  src/app/modules/common/RichEditor/editorStyles.module.css
  src/app/modules/common/RichEditor/extraButtonStyles.css
  src/app/modules/common/RichEditor/index.tsx
  src/app/modules/common/RichEditor/toolbarInvertedStyles.module.css
  src/app/modules/common/RichEditor/toolbarStyles.module.css
  src/app/modules/common/RichEditor/undoButtonStyle.ts
  src/app/modules/report-module/components/reportSubHeaderToolbar/staticToolbar.tsx
  src/app/modules/report-module/sub-module/components/headerBlock/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
  src/app/state/api/action-reducers/sync/charts/index.tsx
  src/app/utils/socialAuth.ts
  src/index.tsx
Labels: size/XL

#78 feat: Updated chart icons and placeholders and fixed some chart issues
  src/app/assets/icons/data-themes-chart-types/areatimeaxis.tsx
  src/app/assets/icons/data-themes-chart-types/coloredAreatimeaxis.tsx
  src/app/assets/icons/data-themes-chart-types/coloredGraphGl.tsx
  src/app/assets/icons/data-themes-chart-types/coloredHeatmap.tsx
  src/app/assets/icons/data-themes-chart-types/coloredRadarChart.tsx
  src/app/assets/icons/data-themes-chart-types/coloredScatterChart.tsx
  src/app/assets/icons/data-themes-chart-types/graphgl.tsx
  src/app/assets/icons/data-themes-chart-types/scatter.tsx
  src/app/hooks/useDataThemesEchart.tsx
  src/app/modules/chart-module/assets/areatimeaxisPlaceholder.svg
  src/app/modules/chart-module/assets/graphglPlaceholder.svg
  src/app/modules/chart-module/assets/graphglPreview.svg
  src/app/modules/chart-module/assets/heatmapPlaceholder.svg
  src/app/modules/chart-module/assets/scatterChartPlaceholder.svg
  src/app/modules/chart-module/assets/scatterChartPreview.svg
  src/app/modules/chart-module/components/placeholder/index.tsx
  src/app/modules/chart-module/routes/chart-type/data.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/utils/getCirclePackingOption.ts
Labels: size/XXL
