Repository zimmerman-team/Dx.client, pull requests merged in 2024-05, with the labels that each got.

#112 feat:DX-1217; adjust assets card in CB
  src/app/modules/home-module/components/Datasets/gridItem.tsx
Labels: size/XS

#119 Feat/external source update
  cypress/e2e/1-dx/2-datasets.cy.ts
  cypress/e2e/1-dx/4-reports.cy.ts
  package.json
  src/app/components/Table/Preview-table/index.tsx
  src/app/components/Table/Preview-table/style.ts
  src/app/hooks/useChartsRawData.tsx
  src/app/hooks/useGetDatasetContent.tsx
  src/app/modules/chart-module/routes/preview/index.tsx
  src/app/modules/dataset-module/routes/datasetDetail/index.tsx
  src/app/modules/dataset-upload-module/__test__/add-dataset.test.tsx
  src/app/modules/dataset-upload-module/__test__/processing.test.tsx
  src/app/modules/dataset-upload-module/assets/close-full-screen.svg
  src/app/modules/dataset-upload-module/assets/full-screen.svg
  src/app/modules/dataset-upload-module/component/data-table/data.ts
  src/app/modules/dataset-upload-module/component/data-table/index.tsx
  src/app/modules/dataset-upload-module/component/dropzone/index.tsx
  src/app/modules/dataset-upload-module/component/stepper.tsx
  src/app/modules/dataset-upload-module/style.ts
  src/app/modules/dataset-upload-module/upload-steps/addDatasetFragment.tsx
  src/app/modules/dataset-upload-module/upload-steps/externalSearch.tsx
  src/app/modules/dataset-upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/dataset-upload-module/upload-steps/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/previewFragment.tsx
  src/app/modules/dataset-upload-module/upload-steps/processing.tsx
  src/app/modules/home-module/assets/hdx-logo.svg
  src/app/modules/home-module/components/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/Datasets/externalDatasetCard.tsx
  src/app/modules/home-module/components/Datasets/gridItem.tsx
  src/app/modules/home-module/index.tsx
  yarn.lock
Labels: size/XXL

#114 Feat/dx 1244
  cypress/e2e/1-dx/2-datasets.cy.ts
  package.json
  src/app/components/Table/Preview-table/index.tsx
  src/app/components/Table/Preview-table/style.ts
  src/app/hooks/useChartsRawData.tsx
  src/app/hooks/useGetDatasetContent.tsx
  src/app/modules/chart-module/routes/preview/index.tsx
  src/app/modules/dataset-module/routes/datasetDetail/index.tsx
  src/app/modules/dataset-upload-module/assets/close-full-screen.svg
  src/app/modules/dataset-upload-module/assets/full-screen.svg
  src/app/modules/dataset-upload-module/component/data-table/data.ts
  src/app/modules/dataset-upload-module/component/data-table/index.tsx
  src/app/modules/dataset-upload-module/style.ts
  src/app/modules/dataset-upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/dataset-upload-module/upload-steps/previewFragment.tsx
  src/app/modules/home-module/components/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/Datasets/gridItem.tsx
  src/app/modules/home-module/index.tsx
  yarn.lock
Labels: size/XL

#120 fix: handle BNC rendering TODO
  src/app/modules/chart-module/index.tsx
Labels: size/XS

#113 feat: Update chart icons in Report RHCP chart view DX-1238
  src/app/modules/report-module/components/right-panel-create-view/data.tsx
Labels: size/XXL

#115 feat: Rephrase the DELETE messaging DX-1112
  src/app/components/Dialogs/deleteDatasetDialog.tsx
  src/app/hooks/useGetChartsReportsCountByDataset.tsx
Labels: size/L

#116 feat: Add the Add Data | Add Chart | Add Report as per DX-1201
  src/app/modules/home-module/index.tsx
Labels: size/XS

#117 feat: DX-1211, DX-1167, DX-1292
  cypress/e2e/1-dx/5-home.cy.ts
  src/app/components/AppBar/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/metaData.tsx
  src/app/modules/home-module/sub-modules/explore-assets/index.tsx
  src/app/modules/home-module/sub-modules/partners/components/empowerBlock.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
Labels: size/M

#121 feat: Add upload steps bar to external search
  src/app/components/Dialogs/deleteChartDialog.tsx
  src/app/modules/dataset-upload-module/upload-steps/externalSearch.tsx
  src/app/modules/dataset-upload-module/upload-steps/index.tsx
  src/app/modules/home-module/components/Charts/chartsGrid.tsx
Labels: size/M

#122 fix: show ai button for data card based on edit access
  src/app/modules/home-module/components/Datasets/gridItem.tsx
Labels: size/M

#123 fix: Truncate Dataset title
  cypress/e2e/1-dx/3-charts.cy.ts
  src/app/modules/dataset-module/component/datasetSubHeaderToolbar.tsx
  src/app/modules/dataset-module/routes/datasetDetail/index.tsx
Labels: size/S

#125 Feat/intercom messenger
  public/index.html
  src/app/Routes.tsx
  src/app/components/Dialogs/logOutDialog.tsx
Labels: size/L

#124 feat: DX-1227 - Implement the Delete Account Flow as per design
  src/app/Routes.tsx
  src/app/components/AppBar/index.tsx
  src/app/components/Dialogs/deleteAccountDialog.tsx
  src/app/modules/user-profile-module/component/tab.tsx
  src/app/modules/user-profile-module/index.tsx
  src/app/modules/user-profile-module/layout.tsx
  src/app/modules/user-profile-module/style.ts
  src/app/modules/user-profile-module/sub-module/profile.tsx
  src/app/modules/user-profile-module/sub-module/settings.tsx
Labels: size/L

#130 Feat/dx 1303
  package.json
  src/app/components/Table/Preview-table/StatisticalRepresentations.tsx
  src/app/components/Table/Preview-table/style.ts
  src/app/hooks/useDataThemesEchart.tsx
  src/app/modules/chart-module/__test__/chart-type.test.tsx
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/components/geomap-legend/index.tsx
  src/app/modules/chart-module/data.ts
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/chart-type/data.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/chart-module/routes/customize/index.tsx
  src/app/modules/chart-module/routes/filters/index.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  yarn.lock
Labels: size/L

#129 feat: visual update for login page
  src/app/modules/onboarding-module/component/card/index.tsx
  src/app/modules/onboarding-module/index.tsx
Labels: size/M

#127 fix/DX-1314; enable drag handle for dividers
  src/app/modules/report-module/components/order-container/index.tsx
Labels: size/XS

#137 fix: Reset offset after search on external search
  src/app/modules/dataset-upload-module/upload-steps/externalSearch.tsx
Labels: size/XS

#138 feat: DX-1434 - Setup intercom messenger for test and staging with th…
  public/index.html
  src/app/Routes.tsx
Labels: size/XS

#132 Feat/dx 1272
  src/app/Routes.tsx
  src/app/modules/home-module/assets/ellipses-2.svg
  src/app/modules/home-module/assets/ellipses.svg
  src/app/modules/home-module/components/Subscribe/index.tsx
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/home-module/sub-modules/explore-assets/index.tsx
  src/app/modules/home-module/sub-modules/landing/assets/interact.png
  src/app/modules/home-module/sub-modules/landing/assets/investment.png
  src/app/modules/home-module/sub-modules/landing/assets/report.png
  src/app/modules/home-module/sub-modules/landing/assets/the-power.png
  src/app/modules/home-module/sub-modules/landing/index.tsx
  src/app/modules/home-module/sub-modules/partners/components/empowerBlock.tsx
  src/app/modules/home-module/sub-modules/partners/style.ts
Labels: size/XL

#135 fix:DX-1424; fix autosave switch state
  src/app/modules/report-module/__test__/reportSubheaderToolbar.test.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/autoSaveSwitch/index.tsx
Labels: size/S

#134 Fix/dx 1418
  package.json
  src/app/modules/chart-module/components/chartSubheaderToolbar/exportButton.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/report-module/__test__/reportSubheaderToolbar.test.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
  src/app/utils/exportPage.ts
  yarn.lock
Labels: size/L

#126 Fix/dx 1375
  src/app/hooks/useChartsRawData.tsx
  src/app/modules/dataset-upload-module/component/data-table/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/index.tsx
Labels: size/M

#131 feat: DX-1281 - Remove duplicate <title> tags
  src/app/modules/callback-module/index.tsx
  src/app/modules/chart-module/routes/preview/index.tsx
  src/app/modules/dataset-module/routes/datasetDetail/index.tsx
  src/app/modules/dataset-module/routes/edit/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/index.tsx
  src/app/modules/home-module/sub-modules/about/index.tsx
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/home-module/sub-modules/explore-assets/index.tsx
  src/app/modules/home-module/sub-modules/partners/index.tsx
  src/app/modules/home-module/sub-modules/why-dx/index.tsx
  src/app/modules/onboarding-module/index.tsx
  src/app/modules/report-module/views/ai-template/index.tsx
  src/app/modules/report-module/views/create/index.tsx
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/initial/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
  src/app/modules/user-profile-module/index.tsx
  src/app/modules/user-profile-module/sub-module/profile.tsx
  src/app/modules/user-profile-module/sub-module/settings.tsx
Labels: size/M

#136 feat: DX-1158 - Implement Pricing Page design
  src/app/Routes.tsx
  src/app/components/AppBar/index.tsx
  src/app/modules/home-module/assets/full-bg-ellipses.svg
  src/app/modules/home-module/sub-modules/pricing/assets/add-chart.tsx
  src/app/modules/home-module/sub-modules/pricing/assets/backup.tsx
  src/app/modules/home-module/sub-modules/pricing/assets/good-icon.tsx
  src/app/modules/home-module/sub-modules/pricing/assets/iati-logo.tsx
  src/app/modules/home-module/sub-modules/pricing/assets/mfa-logo.tsx
  src/app/modules/home-module/sub-modules/pricing/assets/report.tsx
  src/app/modules/home-module/sub-modules/pricing/assets/support.tsx
  src/app/modules/home-module/sub-modules/pricing/assets/tgf-logo.tsx
  src/app/modules/home-module/sub-modules/pricing/assets/user-shied.tsx
  src/app/modules/home-module/sub-modules/pricing/components/faq.tsx
  src/app/modules/home-module/sub-modules/pricing/components/features.tsx
  src/app/modules/home-module/sub-modules/pricing/components/plan-card.tsx
  src/app/modules/home-module/sub-modules/pricing/index.tsx
Labels: size/XXL

#139 Feat/dx 1227
  src/app/components/AppBar/index.tsx
  src/app/modules/user-profile-module/layout.tsx
  src/app/modules/user-profile-module/sub-module/profile.tsx
Labels: size/M

#140 feat: update error handling system in CB
  src/app/hooks/useChartsRawData.tsx
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/components/dialog/errrorComponent.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/customize/data.ts
  src/app/modules/chart-module/routes/customize/index.tsx
  src/app/modules/chart-module/routes/filters/data.ts
  src/app/modules/chart-module/routes/filters/index.tsx
  src/app/modules/chart-module/routes/mapping/data.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/modules/chart-module/routes/preview-theme/data.ts
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/chart-module/routes/preview/index.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
Labels: size/L

#142 Fix/dx 1431/dx 1444
  src/app/hooks/useDataThemesEchart.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/SelectDataset.tsx
Labels: size/S

#141 feat:DX-1410; handle pontential buggy charts from AI suggestion
  src/app/modules/chart-module/components/toolbox/steps/panels-content/Mapping.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/SelectDataset.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/chart-type/data.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
Labels: size/L

#147 Feat/gb 263
  .github/workflows/lint.yml
  .husky/pre-commit
  .prettierignore
  README.md
  package.json
  src/app/components/Buttons/ContainedButton/index.tsx
  src/app/components/Buttons/FilledButton.tsx
  src/app/components/Buttons/TextButton.tsx
  src/app/components/Charts/Budgets/Treemap/data.ts
  src/app/components/Charts/Grants/data.ts
  src/app/components/PerformanceFrameworkExpandedView/components/InterventionsTable/index.tsx
  src/app/components/PerformanceFrameworkExpandedView/data.ts
  src/app/components/Table/Expandable/data.ts
  src/app/modules/chart-module/routes/customize/components/ChartOptionBoolean.js
  src/app/modules/chart-module/routes/customize/components/ChartOptionColorScale.js
  src/app/modules/chart-module/routes/customize/components/ChartOptionColorScaleWrapper.js
  src/app/modules/chart-module/routes/customize/components/ChartOptionNumber.js
  src/app/modules/chart-module/routes/customize/components/ChartOptionRadioGroup.js
  src/app/modules/chart-module/routes/customize/components/ChartOptionSelect.js
  src/app/modules/chart-module/routes/customize/components/ChartOptionText.js
  src/app/modules/chart-module/routes/customize/components/ColorSchemePreview.js
  src/app/modules/chart-module/routes/customize/components/InlineColorPicker/InlineColorPicker.module.css
  src/app/modules/chart-module/routes/customize/components/InlineColorPicker/index.js
  src/app/modules/common/RichEditor/ColorModal/Picker/colorPickerStyles.module.css
  src/app/modules/common/RichEditor/ColorModal/modalStyles.module.css
  src/app/modules/common/RichEditor/alignmentStyles.module.css
  src/app/modules/common/RichEditor/buttonStyles.module.css
  src/app/modules/common/RichEditor/editorStyles.module.css
  src/app/modules/common/RichEditor/extraButtonStyles.css
  src/app/modules/common/RichEditor/toolbarStyles.module.css
  src/app/modules/report-module/components/reportSubHeaderToolbar/autoResizeInput/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/autoSaveSwitch/style.css
  src/app/state/api/action-reducers/cms/componentsAppBar.ts
  src/app/state/api/action-reducers/cms/componentsChartsBudgets.ts
  src/app/state/api/action-reducers/cms/componentsChartsCommon.ts
  src/app/state/api/action-reducers/cms/componentsChartsEligibility.ts
  src/app/state/api/action-reducers/cms/componentsChartsGeomap.ts
  src/app/state/api/action-reducers/cms/componentsChartsGrants.ts
  src/app/state/api/action-reducers/cms/componentsChartsInvestments.ts
  src/app/state/api/action-reducers/cms/componentsChartsNetwork.ts
  src/app/state/api/action-reducers/cms/componentsChartsPerformanceRating.ts
  src/app/state/api/action-reducers/cms/componentsChartsPledges.ts
  src/app/state/api/action-reducers/cms/componentsCookieDialog.ts
  src/app/state/api/action-reducers/cms/componentsDatasetCarousel.ts
  src/app/state/api/action-reducers/cms/componentsInformationPanel.ts
  src/app/state/api/action-reducers/cms/componentsMobile.ts
  src/app/state/api/action-reducers/cms/componentsPageHeader.ts
  src/app/state/api/action-reducers/cms/componentsPerformanceFrameworkComponents.ts
  src/app/state/api/action-reducers/cms/componentsSearch.ts
  src/app/state/api/action-reducers/cms/componentsSlideInPanel.ts
  src/app/theme/rawgraphs.css
  src/app/theme/videoPlayer.css
  src/app/utils/formatBytes.ts
  yarn.lock
Labels: size/XXL

#146 Feat/dx 1442
  src/app/hooks/useChartsRawData.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/Mapping.tsx
  src/app/modules/chart-module/data.ts
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/chart-module/routes/filters/index.tsx
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/chart-module/routes/preview/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
  src/app/state/store/index.ts
  src/app/utils/RouteWithAppBar.tsx
Labels: size/L

#144 feat: allow multi selection for data categories
  src/app/modules/chart-module/routes/data/index.tsx
  src/app/modules/home-module/components/Datasets/datasetCategoryList.tsx
  src/app/modules/home-module/components/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/sub-modules/explore-assets/index.tsx
  src/app/modules/home-module/sub-modules/explore-assets/localAssets.tsx
Labels: size/M

#145 feat: Complete Linkedin Campaign flow
  src/app/modules/callback-module/index.tsx
  src/app/modules/home-module/components/Charts/chartsGrid.tsx
  src/app/modules/home-module/components/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/Reports/reportsGrid.tsx
  src/app/modules/home-module/sub-modules/landing/index.tsx
  src/app/modules/home-module/sub-modules/partners/components/empowerBlock.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/index.tsx
  src/app/modules/report-module/components/use-report-panel/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
Labels: size/L

#143 Fix/dx 1441
  src/app/modules/report-module/components/order-container/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/views/create/index.tsx
  src/app/modules/report-module/views/edit/index.tsx
  src/app/utils/handleAutoScroll.tsx
  src/index.css
Labels: size/L
