Repository zimmerman-team/Dx.client, pull requests merged in 2024-04, with the labels that each got.

#103 feat: terminate pending requests on new search
  src/app/modules/dataset-upload-module/upload-steps/externalSearch.tsx
  src/app/modules/home-module/components/Filter/index.tsx
Labels: size/S

#101 Feat/report media
  .github/workflows/cypress.yml
  cypress/e2e/1-dx/charts.cy.ts
  cypress/e2e/1-dx/reports.cy.ts
  src/app/hooks/useSearchMediaSources.tsx
  src/app/modules/home-module/index.tsx
  src/app/modules/report-module/asset/youtube-gradient.png
  src/app/modules/report-module/asset/youtube-icon.svg
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/style.ts
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
  src/app/modules/report-module/views/create/data.ts
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
  src/index.css
Labels: size/XXL

#102 Feat/update logos
  public/apple-touch-icon.png
  public/logo.svg
  public/logo192.png
  public/logo512.png
  public/mstile-150x150.png
  src/app/modules/home-module/components/Footer/asset/logo.svg
Labels: size/M

#91 feat: Setup flow for duplication of assets on user signup
  src/app/modules/callback-module/index.tsx
Labels: size/S

#106 DX-1286: non-owner user not able to edit chart
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/components/toolbox/index.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/chart-module/routes/customize/index.tsx
  src/app/modules/chart-module/routes/data/index.tsx
  src/app/modules/chart-module/routes/filters/index.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/modules/chart-module/routes/preview/index.tsx
  src/app/modules/common/not-authorized-message/index.tsx
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
Labels: size/L

#108 Feat/chart builder updates
  src/app/components/Table/Preview-table/index.tsx
  src/app/hooks/useChartsRawData.tsx
  src/app/hooks/useDataThemesEchart.tsx
  src/app/modules/chart-module/__test__/chart-type.test.tsx
  src/app/modules/chart-module/__test__/chartSubheaderToolbar.test.tsx
  src/app/modules/chart-module/__test__/filter.test.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/components/toolbox/data.tsx
  src/app/modules/chart-module/components/toolbox/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/Mapping.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/SelectDataset.tsx
  src/app/modules/chart-module/components/toolbox/styles.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/chart-type/data.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/chart-module/routes/customize/data.ts
  src/app/modules/chart-module/routes/data/index.tsx
  src/app/modules/chart-module/routes/filters/components/FilterGroup.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/chart-module/routes/preview/index.tsx
  src/app/modules/dataset-module/data.ts
  src/app/modules/dataset-module/routes/datasetDetail/index.tsx
  src/app/modules/dataset-upload-module/component/data-table/data.ts
  src/app/modules/dataset-upload-module/component/data-table/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/dataset-upload-module/upload-steps/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/previewFragment.tsx
  src/app/modules/home-module/components/Charts/chartsGrid.tsx
  src/app/modules/home-module/components/Charts/gridItem.tsx
  src/app/modules/home-module/components/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/Datasets/gridItem.tsx
  src/app/modules/home-module/components/Reports/gridItem.tsx
  src/app/modules/home-module/components/Reports/reportsGrid.tsx
  src/app/modules/report-module/__test__/reportRightPanelCreateView.test.tsx
  src/app/modules/report-module/__test__/reportSubheaderToolbar.test.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/data.tsx
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/rhpGridItem.tsx
  src/app/modules/report-module/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/style.ts
  src/app/state/api/action-reducers/charts/index.ts
  src/app/state/api/interfaces/index.ts
  src/app/state/recoil/atoms/index.ts
  src/app/state/store/index.ts
Labels: size/XXL

#109 Feat/e2e testing
  cypress/e2e/1-dx/1-test-login.cy.ts
  cypress/e2e/1-dx/2-datasets.cy.ts
  cypress/e2e/1-dx/3-charts.cy.ts
  cypress/e2e/1-dx/4-reports.cy.ts
  src/app/hooks/useChartsRawData.tsx
  src/app/modules/chart-module/components/toolbox/index.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/addRowFrameButton.tsx
  src/app/modules/report-module/sub-module/rowStructure/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
  src/app/modules/report-module/views/edit/index.tsx
Labels: size/XL

#110 Fix/tests
  .github/workflows/cypress.yml
  .github/workflows/tests.yml
  package.json
  src/app/modules/chart-module/__test__/chart-type.test.tsx
  src/app/modules/chart-module/__test__/chartSubheaderToolbar.test.tsx
  src/app/modules/report-module/__test__/data.ts
  src/app/modules/report-module/__test__/reportRightPanelCreateView.test.tsx
Labels: size/L

#111 fix: mapping error
  src/app/hooks/useChartsRawData.tsx
Labels: size/XS
