Repository zimmerman-team/Dx.client, pull requests merged in 2024-12, with the labels that each got.

#271 fix:minor-updates
  src/app/assets/icons/AIIcon.tsx
  src/app/components/Dialogs/EmbedChartDialog/index.tsx
  src/app/components/Dialogs/EmbedChartDialog/shareContent.tsx
  src/app/modules/chart-module/components/toolbox/steps/sub-header.tsx
  src/app/modules/chart-module/routes/customize/index.tsx
  src/app/modules/chart-module/routes/filters/index.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/home-module/assets/about-card.png
  src/app/modules/home-module/assets/budgets-card.png
  src/app/modules/home-module/assets/grants-card.png
  src/app/modules/home-module/assets/targets-result.png
  src/app/modules/home-module/assets/targets-results.png
  src/app/modules/home-module/components/AssetCollection/Charts/gridItem.tsx
  src/app/modules/home-module/sub-modules/partners/components/tabCard.tsx
  src/app/modules/onboarding-module/asset/onboardingRight-img.png
  src/app/modules/onboarding-module/asset/onboardingRight-img.svg
  src/app/modules/onboarding-module/index.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/panelLabel.tsx
  src/app/modules/report-module/components/right-panel-create-view/rhpGridItem.tsx
  src/app/modules/user-profile-module/component/table.tsx
Labels: size/L

#273 feat: DX-2107 - Connect Newsletter subscription to intercom
  src/app/modules/common/newsletterForm/index.tsx
Labels: size/S

#274 Feat/dx 2011
  src/app/components/AppBar/index.tsx
  src/app/components/Dialogs/deleteDatasetDialog.tsx
  src/app/modules/home-module/assets/add-icon.svg
  src/app/modules/home-module/assets/budget-chart.png
  src/app/modules/home-module/assets/budget-data.png
  src/app/modules/home-module/assets/build-reports-illustration.svg
  src/app/modules/home-module/assets/chunk-eye.svg
  src/app/modules/home-module/assets/climate-report.png
  src/app/modules/home-module/assets/collaborate-illustration.svg
  src/app/modules/home-module/assets/connect-seamlessly-illustration.svg
  src/app/modules/home-module/assets/creat-report-illustration.svg
  src/app/modules/home-module/assets/create-charts-illustration.svg
  src/app/modules/home-module/assets/gender-report.png
  src/app/modules/home-module/assets/google-icon-flat.svg
  src/app/modules/home-module/assets/hero-ellipses.svg
  src/app/modules/home-module/assets/iati-country-chart.png
  src/app/modules/home-module/assets/linkedIn-icon-flat.svg
  src/app/modules/home-module/assets/malaria-report.png
  src/app/modules/home-module/assets/microsoft-icon-flat.svg
  src/app/modules/home-module/assets/open-lock-icon.svg
  src/app/modules/home-module/assets/report-illustration.svg
  src/app/modules/home-module/assets/saveTime-illustration.svg
  src/app/modules/home-module/assets/share-insights-illustration.svg
  src/app/modules/home-module/assets/upload-data-illustration.svg
  src/app/modules/home-module/assets/visualise-illustration.svg
  src/app/modules/home-module/components/hero/index.tsx
  src/app/modules/home-module/components/nonAuthUserLibrary/assetsList.tsx
  src/app/modules/home-module/components/nonAuthUserLibrary/coreFeaturesCard.tsx
  src/app/modules/home-module/components/nonAuthUserLibrary/extraFeaturesCard.tsx
  src/app/modules/home-module/components/nonAuthUserLibrary/index.tsx
  src/app/modules/home-module/components/nonAuthUserLibrary/infoCard.tsx
  src/app/modules/home-module/components/nonAuthUserLibrary/panel.tsx
  src/app/modules/home-module/components/nonAuthUserLibrary/signupDialog.tsx
  src/app/modules/home-module/components/nonAuthUserLibrary/style.ts
  src/app/modules/home-module/index.tsx
Labels: size/XXL

#275 feat: DX-2113 - Fix JSON File upload
  src/app/modules/dataset-module/routes/upload-module/component/dropzone/index.tsx
Labels: size/XS

#276 Feat/dx 2100
  src/app/components/Dialogs/deleteChartDialog.tsx
  src/app/components/Dialogs/deleteDatasetDialog.tsx
  src/app/components/Dialogs/deleteReportDialog.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/dataset-module/component/datasetSubHeaderToolbar.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/index.tsx
Labels: size/M

#277 feat: persist sort by state in external data search
  src/app/modules/dataset-module/routes/upload-module/upload-steps/externalSearch.tsx
  src/app/state/recoil/atoms/index.ts
Labels: size/S

#272 Chore/remove vscode settings
  .gitignore
  .vscode/settings.json
Labels: size/XS

#280 chore: update copy changes
  cypress/e2e/2-datasets.cy.ts
  src/app/modules/dataset-module/routes/upload-module/component/tabs.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/externalSearch.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/index.tsx
  src/app/modules/home-module/components/hero/index.tsx
  src/app/modules/home-module/components/nonAuthUserLibrary/extraFeaturesCard.tsx
  src/app/modules/home-module/sub-modules/pricing/components/features.tsx
Labels: size/S
