Repository zimmerman-team/Dx.client, pull requests merged in 2024-08, with the labels that each got.

#205 fix: DX-1713 - Fix scatter chart plotting
  src/app/hooks/useDataThemesEchart.tsx
Labels: size/S

#207 feat: Add yarn cache to github actions to reduce test run time
  .github/workflows/tests.yml
Labels: size/S

#208 feat:DX-1567; implement microsoft sign in
  src/app/Routes.tsx
  src/app/components/Dialogs/EmbedChartDialog/assets/facebook.svg
  src/app/components/Dialogs/EmbedChartDialog/assets/instagram.svg
  src/app/components/Dialogs/EmbedChartDialog/assets/linkedIn.svg
  src/app/components/Dialogs/EmbedChartDialog/assets/twitter.svg
  src/app/components/Dialogs/EmbedChartDialog/chartContainer.tsx
  src/app/components/Dialogs/EmbedChartDialog/copyButton.tsx
  src/app/components/Dialogs/EmbedChartDialog/embedOptions.tsx
  src/app/components/Dialogs/EmbedChartDialog/index.tsx
  src/app/components/Dialogs/EmbedChartDialog/linkOptions.tsx
  src/app/components/Dialogs/EmbedChartDialog/shareContent.tsx
  src/app/components/Dialogs/deleteAccountDialog.tsx
  src/app/components/Dialogs/deleteChartDialog.tsx
  src/app/components/Dialogs/deleteDatasetDialog.tsx
  src/app/components/Dialogs/deleteReportDialog.tsx
  src/app/components/Inputs/NumberInput.tsx
  src/app/components/SlideInPanel/index.tsx
  src/app/components/Switch/BasicSwitch/index.tsx
  src/app/components/ToggleButton/toggleButtonGroup.tsx
  src/app/index.tsx
  src/app/modules/chart-module/__test__/chartSubheaderToolbar.test.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/common/no-match-page/index.tsx
  src/app/modules/dataset-module/routes/upload-module/component/uploadOption.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/index.tsx
  src/app/modules/embed-module/embedChart/index.tsx
  src/app/modules/home-module/index.tsx
  src/app/modules/onboarding-module/asset/microsoft-img.svg
  src/app/modules/onboarding-module/component/card/index.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  src/app/modules/report-module/components/chart-wrapper/useLoadDatasetDetailsAPI.tsx
  src/app/modules/report-module/components/chart-wrapper/useRenderChartFromAPI.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
  src/app/utils/copyToClipboard.ts
  src/app/utils/handleAutoScroll.ts
Labels: size/XXL

#206 feat: DX-1703 - Fix not authorized page blinking
  src/app/modules/chart-module/index.tsx
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
Labels: size/M

#211 Feat/dx 1707/dx 1709
  src/app/modules/home-module/components/AssetCollection/index.tsx
  src/app/modules/home-module/index.tsx
Labels: size/L

#213 fix: add required packages
  package.json
  yarn.lock
Labels: size/M

#214 feat: DX-1594 - Downloading PDF size is 300% by default
  src/app/utils/exportPage.ts
Labels: size/S

#215 fix: preview chart logic
  src/app/modules/chart-module/__test__/chartSubheaderToolbar.test.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/data.ts
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/preview-theme/data.ts
  src/app/modules/chart-module/routes/preview-theme/index.tsx
Labels: size/L

#217 chore: refactor code
  src/app/components/Dialogs/EmbedChartDialog/chartContainer.tsx
  src/app/components/Dialogs/EmbedChartDialog/index.tsx
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/data.ts
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/chart-type/data.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/chart-module/routes/customize/data.ts
  src/app/modules/chart-module/routes/customize/index.tsx
  src/app/modules/chart-module/routes/filters/data.ts
  src/app/modules/chart-module/routes/filters/index.tsx
  src/app/modules/chart-module/routes/mapping/data.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/modules/chart-module/routes/preview-theme/data.ts
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/embed-module/embedChart/index.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  src/app/state/api/action-reducers/sync/charts/index.tsx
Labels: size/L
