Repository zimmerman-team/Dx.client, pull requests merged in 2024-06, with the labels that each got.

#151 chore: add TGF as option for external search results
  src/app/modules/dataset-upload-module/upload-steps/externalSearch.tsx
  src/app/modules/home-module/assets/tgf-logo.svg
  src/app/modules/home-module/components/Datasets/externalDatasetCard.tsx
Labels: size/M

#148 Feat/base report DX-1420
  src/app/Providers.tsx
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/common/RichEditor/FontSizeController/index.tsx
  src/app/modules/common/RichEditor/FontSizeController/styleMap.ts
  src/app/modules/common/RichEditor/index.tsx
  src/app/modules/dataset-module/data.ts
  src/app/modules/dataset-module/routes/datasetDetail/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/dataset-upload-module/upload-steps/index.tsx
  src/app/modules/home-module/components/Footer/index.tsx
  src/app/modules/home-module/components/Footer/smallFooter.tsx
  src/app/modules/home-module/components/Footer/style.ts
  src/app/modules/home-module/sub-modules/about/index.tsx
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/home-module/sub-modules/landing/index.tsx
  src/app/modules/home-module/sub-modules/partners/index.tsx
  src/app/modules/home-module/sub-modules/pricing/index.tsx
  src/app/modules/home-module/sub-modules/why-dx/index.tsx
  src/app/modules/report-module/components/order-container/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/autoResizeInput/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/staticToolbar.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/styles.ts
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/data.ts
  src/app/modules/report-module/sub-module/rowStructure/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
  src/app/modules/report-module/views/create/index.tsx
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
  src/app/state/recoil/atoms/index.ts
Labels: size/XXL

#153 feat:DX-1518;retain btr state when creating dataset
  src/app/modules/chart-module/components/toolbox/steps/panels-content/SelectDataset.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/finishedFragment.tsx
Labels: size/M

#154 fix:DX-1482; fix text content resize bug
  src/app/modules/common/RichEditor/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
Labels: size/M

#152 feat: DX-1501 - Replace current Contact Form with Intercom Form fields
  src/app/modules/home-module/sub-modules/contact/index.tsx
Labels: size/M

#157 fix:DX-1511; adjust login alignment
  src/app/modules/onboarding-module/index.tsx
Labels: size/XS

#156 feat: DX-1550 Pagination for report media
  src/app/hooks/useInfinityScroll.ts
  src/app/hooks/useSearchMediaSources.tsx
  src/app/modules/report-module/__test__/reportRightPanelCreateView.test.tsx
  src/app/modules/report-module/__test__/setupIntersectionObserver.ts
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
Labels: size/L

#155 feat: DX-1504, DX-1552, DX-1502 Not authorized page view
  src/app/hooks/useChartsRawData.tsx
  src/app/hooks/useGetDatasetContent.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/chart-module/routes/data/index.tsx
  src/app/modules/chart-module/routes/preview/index.tsx
  src/app/modules/common/not-authorized-message/index.tsx
  src/app/modules/dataset-module/routes/datasetDetail/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/index.tsx
  src/app/modules/home-module/components/Breadcrumbs/index.tsx
  src/app/modules/report-module/index.tsx
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
Labels: size/L

#158 feat: DX-1531, DX-1530, DX-1528
  src/app/hooks/useDataThemesEchart.tsx
Labels: size/M

#160 Fix/test release fixes
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/autoResizeInput/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
Labels: size/S

#163 Feat/dx 1560
  src/app/Routes.tsx
  src/app/components/AppBar/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/externalSearch.tsx
  src/app/modules/dataset-upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/dataset-upload-module/upload-steps/index.tsx
  src/app/modules/home-module/assets/dataset-detail.png
  src/app/modules/home-module/assets/hero-ellipses.svg
  src/app/modules/home-module/components/AssetCollection/index.tsx
  src/app/modules/home-module/components/Datasets/gridItem.tsx
  src/app/modules/home-module/components/Table/index.tsx
  src/app/modules/home-module/index.tsx
  src/app/modules/home-module/style.ts
  src/app/modules/home-module/sub-modules/dashboard/index.tsx
  src/app/state/recoil/atoms/index.ts
Labels: size/XXL

#161 Fix/test release fixes
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/externalSearch.tsx
  src/app/modules/dataset-upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  src/app/modules/report-module/components/chart-wrapper/useLoadDatasetDetailsAPI.tsx
  src/app/modules/report-module/index.tsx
Labels: size/L

#164 Fix/dx 1586
  src/app/hooks/useChartsRawData.tsx
Labels: size/XS

#166 fix: offset error in pagination
  src/app/modules/dataset-upload-module/component/externalSourcesList.tsx
  src/app/modules/dataset-upload-module/upload-steps/externalSearch.tsx
Labels: size/XS

#169 Feat/dx 1576/dx 1577/dx 1588
  src/app/modules/dataset-module/routes/edit/index.tsx
  src/app/modules/dataset-upload-module/style.ts
  src/app/modules/dataset-upload-module/upload-steps/index.tsx
  src/app/modules/home-module/assets/table-icon.svg
  src/app/modules/home-module/components/AssetCollection/index.tsx
  src/app/modules/home-module/components/Filter/index.tsx
  src/app/modules/home-module/style.ts
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
Labels: size/M

#168 feat: update routing logic and implement private route
  src/app/Routes.tsx
  src/app/components/Table/Preview-table/index.tsx
  src/app/modules/callback-module/index.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/customize/index.tsx
  src/app/modules/chart-module/routes/data/index.tsx
  src/app/modules/chart-module/routes/filters/index.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/modules/common/not-authorized-message/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/index.tsx
  src/app/modules/home-module/components/All/assetsGrid.tsx
  src/app/modules/home-module/components/Charts/chartsGrid.tsx
  src/app/modules/home-module/components/Charts/gridItem.tsx
  src/app/modules/home-module/components/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/Datasets/gridItem.tsx
  src/app/modules/home-module/components/Reports/gridItem.tsx
  src/app/modules/home-module/components/Reports/reportsGrid.tsx
  src/app/modules/home-module/components/Table/index.tsx
  src/app/modules/onboarding-module/component/card/index.tsx
  src/app/modules/report-module/views/create/index.tsx
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/initial/index.tsx
  src/app/utils/AuthProtectedRoute.tsx
  src/app/utils/socialAuth.ts
Labels: size/L

#167 fix: DX-1598 - Years on axis strangeness
  src/app/hooks/useDataThemesEchart.tsx
Labels: size/XS

#170 Feat/dx 1548
  src/app/modules/common/RichEditor/FontSizeController/index.tsx
  src/app/modules/common/RichEditor/FontSizeController/styleMap.ts
  src/app/modules/common/RichEditor/buttonStyles.module.css
  src/app/modules/common/RichEditor/buttons.tsx
  src/app/modules/common/RichEditor/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/staticToolbar.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/styles.ts
Labels: size/L
