Repository zimmerman-team/Dx.client, pull requests merged in 2024-09, with the labels that each got.

#222 chore: update livesession tag
  public/index.html
Labels: size/XS

#223 Develop
  public/index.html
Labels: size/XS

#225 fix: intercom messenger prod
  src/app/Routes.tsx
Labels: size/XS

#226 Develop
  src/app/Routes.tsx
Labels: size/XS

#228 fix: intercom messenger not dislayed in prod
  src/app/Routes.tsx
Labels: size/XS

#229 Develop
  src/app/Routes.tsx
Labels: size/XS

#224 chore: use livesession sdk
  package.json
  public/index.html
  src/app/Routes.tsx
  src/app/hooks/useRouteListener.ts
  yarn.lock
Labels: size/S

#230 Develop
  package.json
  public/index.html
  src/app/Routes.tsx
  src/app/hooks/useRouteListener.ts
  yarn.lock
Labels: size/S

#231 fix: Issue with Federated search scrolling/loading assets
  src/app/Routes.tsx
  src/app/hooks/useCheckUserPlan.tsx
  src/app/hooks/useOneDrivePicker.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/externalSearch.tsx
  src/app/state/recoil/atoms/index.ts
Labels: size/M

#232 Feat/dx 1801
  src/app/hooks/useOneDrivePicker.tsx
Labels: size/XS

#234 Develop
  src/app/Routes.tsx
  src/app/hooks/useCheckUserPlan.tsx
  src/app/hooks/useOneDrivePicker.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/externalSearch.tsx
  src/app/state/recoil/atoms/index.ts
Labels: size/M

#227 feat: fill incomplete table with empty cells
  cypress/e2e/1-dx/2-datasets.cy.ts
  cypress/e2e/1-dx/3-charts.cy.ts
  cypress/e2e/1-dx/4-reports.cy.ts
  src/app/components/Table/Preview-table/index.tsx
  src/app/utils/setMediaQueryForTest 2.ts
Labels: size/M

#233 feat:DX-1615; implement 404 logic
  src/app/modules/chart-module/components/toolbox/index.tsx
  src/app/modules/chart-module/data.ts
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/select-data/index.tsx
  src/app/modules/common/no-match-page/asset/404.svg
  src/app/modules/common/no-match-page/asset/bg-ellipse.svg
  src/app/modules/common/no-match-page/index.tsx
  src/app/modules/dataset-module/index.tsx
  src/app/modules/report-module/index.tsx
Labels: size/L

#236 feat: get chart owner
  src/app/components/Dialogs/EmbedChartDialog/index.tsx
  src/app/state/api/action-reducers/user/index.ts
  src/app/state/api/interfaces/index.ts
  src/app/state/store/index.ts
Labels: size/M

#235 Feat/report header
  cypress/e2e/1-dx/4-reports.cy.ts
  src/app/modules/chart-module/components/chartSubheaderToolbar/data.ts
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/common/RichEditor/index.tsx
  src/app/modules/home-module/__test__/reportCard.test.tsx
  src/app/modules/home-module/components/AssetCollection/All/assetsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Charts/chartsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Reports/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/Reports/reportsGrid.tsx
  src/app/modules/home-module/components/Table/index.tsx
  src/app/modules/report-module/__test__/headerBlock.test.tsx
  src/app/modules/report-module/__test__/reportSubheaderToolbar.test.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/components/right-panel/data.ts
  src/app/modules/report-module/data.ts
  src/app/modules/report-module/index.tsx
  src/app/modules/report-module/sub-module/components/headerBlock/index.tsx
  src/app/modules/report-module/sub-module/components/headerBlock/style.ts
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
  src/app/modules/report-module/views/create/data.ts
  src/app/modules/report-module/views/create/index.tsx
  src/app/modules/report-module/views/edit/compareStates.ts
  src/app/modules/report-module/views/edit/data.ts
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
  src/app/state/recoil/atoms/index.ts
Labels: size/XL

#237 style: apply z-index
  src/app/modules/common/no-match-page/index.tsx
Labels: size/XS
