Repository zimmerman-team/Dx.client, pull requests merged in 2024-03, with the labels that each got.

#90 Fix/scatter chart
  src/app/hooks/useDataThemesEchart.tsx
Labels: size/M

#88 Feat/dx 1082
  src/app/hooks/useChartsRawData.tsx
  src/app/modules/chart-module/components/toolbox/data.ts
  src/app/modules/chart-module/components/toolbox/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/SelectDataset.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/rhpGridItem.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
  src/app/state/api/interfaces/index.ts
Labels: size/L

#83 feat:dataset upload tests
  package.json
  src/app/Routes.tsx
  src/app/assets/icons/data-themes-chart-types/circlepacking.tsx
  src/app/assets/icons/data-themes-chart-types/circulargraph.tsx
  src/app/assets/icons/data-themes-chart-types/forcegraph.tsx
  src/app/assets/icons/data-themes-chart-types/heatmap.tsx
  src/app/assets/icons/data-themes-chart-types/pie.tsx
  src/app/assets/icons/data-themes-chart-types/scatter.tsx
  src/app/components/Dialogs/deleteChartDialog.tsx
  src/app/hooks/useChartsRawData.tsx
  src/app/hooks/useDataThemesEchart.tsx
  src/app/modules/chart-module/__test__/chart-type.test.tsx
  src/app/modules/chart-module/__test__/chartSubheaderToolbar.test.tsx
  src/app/modules/chart-module/__test__/data.ts
  src/app/modules/chart-module/__test__/filter.test.tsx
  src/app/modules/chart-module/__test__/navbar.test.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/data.ts
  src/app/modules/chart-module/components/chartSubheaderToolbar/exportButton.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/components/toolbox/data.tsx
  src/app/modules/chart-module/components/toolbox/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/navbar/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/navbar/style.ts
  src/app/modules/chart-module/components/toolbox/steps/panels-content/Filters.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/chart-module/routes/filters/components/ExpandedFilterGroup.tsx
  src/app/modules/chart-module/routes/filters/components/FilterGroup.tsx
  src/app/modules/dataset-module/component/datasetSubHeaderToolbar.tsx
  src/app/modules/dataset-upload-module/__test__/add-dataset.test.tsx
  src/app/modules/dataset-upload-module/__test__/metadata.test.tsx
  src/app/modules/dataset-upload-module/__test__/mock-data.ts
  src/app/modules/dataset-upload-module/__test__/processing.test.tsx
  src/app/modules/dataset-upload-module/component/dropzone/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/addDatasetFragment.tsx
  src/app/modules/dataset-upload-module/upload-steps/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/metaData.tsx
  src/app/modules/dataset-upload-module/upload-steps/processing.tsx
  src/app/modules/home-module/index.tsx
  src/app/modules/report-module/__test__/report-subheader-toolbar.test.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/autoResizeInput/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/autoSaveSwitch/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/infosnackbar.tsx
  src/app/modules/report-module/index.tsx
  src/app/state/api/action-reducers/data-themes/index.ts
  src/app/state/api/action-reducers/sync/charts/index.tsx
  src/app/state/api/interfaces/index.ts
  src/app/state/store/index.ts
  src/app/utils/mockAuth0.ts
  src/app/utils/recoilObserver.ts
  src/setupTests.js
  test/.gitignore
  tsconfig.json
  yarn.lock
Labels: size/XXL

#93 feat: DX-1132; DX-1130; added linkedln tracker tags
  public/index.html
Labels: size/S

#92 Feat/unit testing
  src/app/components/Dialogs/CookieDialog/index.tsx
  src/app/components/Dialogs/deleteReportDialog.tsx
  src/app/components/Styled/tabs.ts
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/dataset-module/component/datasetSubHeaderToolbar.tsx
  src/app/modules/home-module/components/Charts/gridItem.tsx
  src/app/modules/home-module/components/Reports/gridItem.tsx
  src/app/modules/home-module/style.ts
  src/app/modules/home-module/sub-modules/about/style.ts
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/home-module/sub-modules/explore-assets/index.tsx
  src/app/modules/home-module/sub-modules/partners/components/bestDecisionBlock.tsx
  src/app/modules/home-module/sub-modules/partners/components/tabCard.tsx
  src/app/modules/home-module/sub-modules/partners/style.ts
  src/app/modules/report-module/__test__/headerBlock.test.tsx
  src/app/modules/report-module/__test__/reportSubheaderToolbar.test.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/index.tsx
  src/app/modules/report-module/sub-module/components/headerBlock/index.tsx
  src/app/modules/report-module/views/ai-template/style.ts
  src/app/modules/report-module/views/initial/index.tsx
  src/index.css
Labels: size/L

#94 fix: sort the x axis data on the time axis
  src/app/hooks/useDataThemesEchart.tsx
Labels: size/XS

#95 feat: Option to toggle Antartica on and off on geomap
  src/app/hooks/useDataThemesEchart.tsx
Labels: size/S

#96 update unit tests and bug fixes
  src/app/hooks/useChartsRawData.tsx
  src/app/modules/chart-module/__test__/chartSubheaderToolbar.test.tsx
  src/app/modules/report-module/__test__/data.ts
  src/app/modules/report-module/__test__/headerBlock.test.tsx
  src/app/modules/report-module/__test__/reportRightPanelCreateView.test.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/data.tsx
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/rhpGridItem.tsx
  src/app/modules/report-module/sub-module/components/headerBlock/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
  src/app/state/api/index.ts
Labels: size/XXL

#97 Fix/dx 1109
  src/app/modules/chart-module/components/toolbox/steps/panels-content/Mapping.tsx
  src/app/modules/chart-module/components/toolbox/styles.ts
Labels: size/L

#98 feat:DX-1068; terminate requests of ext. search exit
  package.json
  src/app/modules/dataset-upload-module/upload-steps/externalSearch.tsx
Labels: size/S

#99 Feat/small features requests
  src/app/components/Dialogs/TourGuide/index.tsx
  src/app/components/Dialogs/TourGuide/rowFrameIntro.tsx
  src/app/components/Dialogs/TourGuide/selectStructure.tsx
  src/app/components/Dialogs/TourGuide/tourEnd.tsx
  src/app/components/Styled/tabs.ts
  src/app/modules/chart-module/components/toolbox/steps/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/ChartType.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/Filters.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/Mapping.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/SelectDataset.tsx
  src/app/modules/chart-module/components/toolbox/steps/sub-header.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/filters/components/ExpandedFilterGroup.tsx
  src/app/modules/common/newsletterForm/index.tsx
  src/app/modules/common/not-authorized-message/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/dataset-upload-module/upload-steps/metaData.tsx
  src/app/modules/dataset-upload-module/upload-steps/processing.tsx
  src/app/modules/home-module/components/Datasets/gridItem.tsx
  src/app/modules/home-module/sub-modules/about/components/teamBlock.tsx
  src/app/modules/home-module/sub-modules/about/style.ts
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/home-module/sub-modules/partners/components/useDXBlock.tsx
  src/app/modules/home-module/sub-modules/partners/style.ts
  src/app/modules/home-module/sub-modules/why-dx/components/benefitsBlock.tsx
  src/app/modules/home-module/sub-modules/why-dx/components/keyFeaturesBlock.tsx
  src/app/modules/home-module/sub-modules/why-dx/components/tryUsBlock.tsx
  src/app/modules/home-module/sub-modules/why-dx/index.tsx
  src/app/modules/home-module/sub-modules/why-dx/style.ts
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/autoSaveSwitch/style.css
  src/app/modules/report-module/components/reportSubHeaderToolbar/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/panelLabel.tsx
  src/app/modules/report-module/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/addRowFrameButton.tsx
  src/app/modules/report-module/sub-module/rowStructure/index.tsx
  src/app/modules/report-module/views/ai-template/index.tsx
  src/app/modules/report-module/views/ai-template/style.ts
  src/app/modules/report-module/views/create/index.tsx
  src/app/modules/report-module/views/edit/data.ts
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/initial/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
Labels: size/XL

#100 Feat/e2e testing
  .github/workflows/cypress.yml
  .gitignore
  cypress.config.ts
  cypress/e2e/1-dx/1-test-login.cy.ts
  cypress/e2e/1-dx/2-datasets.cy.ts
  cypress/e2e/1-dx/charts.cy.ts
  cypress/e2e/1-dx/reports.cy.ts
  cypress/fixtures/example.json
  cypress/fixtures/football-players.csv
  cypress/global.d.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/support/index.ts
  package.json
  src/app/Routes.tsx
  src/app/components/AppBar/index.tsx
  src/app/components/Dialogs/CookieDialog/index.tsx
  src/app/components/Dialogs/TourGuide/tourStart.tsx
  src/app/components/Dialogs/deleteChartDialog.tsx
  src/app/components/Dialogs/deleteDatasetDialog.tsx
  src/app/components/Dialogs/deleteReportDialog.tsx
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/navbar/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/ChartType.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/Mapping.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/SelectDataset.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/common/RichEditor/index.tsx
  src/app/modules/dataset-upload-module/component/dropzone/index.tsx
  src/app/modules/dataset-upload-module/upload-steps/metaData.tsx
  src/app/modules/home-module/components/Charts/chartsGrid.tsx
  src/app/modules/home-module/components/Charts/gridItem.tsx
  src/app/modules/home-module/components/Datasets/externalDatasetCard.tsx
  src/app/modules/home-module/components/Datasets/gridItem.tsx
  src/app/modules/home-module/components/Filter/index.tsx
  src/app/modules/home-module/components/Reports/gridItem.tsx
  src/app/modules/home-module/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/autoResizeInput/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/index.tsx
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/sub-module/components/headerBlock/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
  src/app/modules/report-module/views/create/index.tsx
  src/app/modules/report-module/views/initial/data.tsx
  tsconfig.json
  yarn.lock
Labels: size/XXL
