Repository zimmerman-team/Dx.client, pull requests merged in 2024-07, with the labels that each got.

#181 feat: add new html file
  public/astra-46d96db2-a64d-45dc-9710-9dd6ef7878b1.html
Labels: size/XS

#182 chore: setup button link to auth0 username/pass
  src/app/modules/home-module/components/Footer/index.tsx
Labels: size/S

#174 fix:DX-1612; fix datasets filter bug
  src/app/assets/icons/data-themes-chart-types/coloredAreastacked.tsx
  src/app/assets/icons/data-themes-chart-types/coloredAreatimeaxis.tsx
  src/app/assets/icons/data-themes-chart-types/coloredBubbleChart.tsx
  src/app/modules/common/RichEditor/buttons.tsx
  src/app/modules/dataset-module/routes/edit/index.tsx
  src/app/modules/dataset-upload-module/assets/upload-options-icons/hubspot.tsx
  src/app/modules/dataset-upload-module/assets/upload-options-icons/mongodb.tsx
  src/app/modules/dataset-upload-module/assets/upload-options-icons/postgres.tsx
  src/app/modules/home-module/components/Datasets/datasetsGrid.tsx
  src/app/modules/report-module/components/right-panel-create-view/data.tsx
Labels: size/XL

#177 Feat/dx 1619
  src/app/hooks/useAutoSave.tsx
  src/app/hooks/useUpdateEffectOnce.tsx
  src/app/modules/chart-module/__test__/chart-type.test.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/components/toolbox/data.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/SelectDataset.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/chart-type/data.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/chart-module/routes/filters/index.tsx
  src/app/modules/chart-module/routes/preview/index.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  src/app/modules/report-module/components/chart-wrapper/useLoadDatasetDetailsAPI.tsx
  src/app/modules/report-module/data.ts
  src/app/modules/report-module/index.tsx
  src/app/modules/report-module/sub-module/components/headerBlock/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/addRowFrameButton.tsx
  src/app/modules/report-module/sub-module/rowStructure/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
  src/app/modules/report-module/views/create/index.tsx
  src/app/modules/report-module/views/edit/compareStates.ts
  src/app/modules/report-module/views/edit/data.ts
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
Labels: size/XL

#172 feat: validate source url field
  cypress/e2e/1-dx/2-datasets.cy.ts
  src/app/modules/dataset-upload-module/upload-steps/metaData.tsx
  src/app/utils/emailValidation.ts
Labels: size/M

#178 Fix/dx 1581
  src/app/components/Dialogs/deleteAccountDialog.tsx
  src/app/components/Dialogs/deleteChartDialog.tsx
  src/app/components/Dialogs/deleteDatasetDialog.tsx
  src/app/components/Dialogs/deleteReportDialog.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/chart-module/routes/customize/index.tsx
  src/app/modules/chart-module/routes/data/index.tsx
  src/app/modules/chart-module/routes/filters/index.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/modules/chart-module/routes/preview/index.tsx
  src/app/modules/common/not-authorized-message/index.tsx
  src/app/modules/report-module/views/edit/index.tsx
Labels: size/XL

#188 ajdust flow after connect dataset is through
  src/app/modules/dataset-upload-module/upload-steps/finishedFragment.tsx
Labels: size/S

#180 fix: When Google drive is not connected and user connects and picks a…
  src/app/hooks/useGoogleDrivePicker.tsx
  src/app/modules/dataset-upload-module/upload-steps/addDatasetFragment.tsx
  src/app/utils/getCookie.ts
Labels: size/S

#183 fix: DX-1641 - E-mail address issue
  src/app/modules/common/newsletterForm/index.tsx
Labels: size/S

#189 feat: DX-1493; persist states in assets overview
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/routes/data/index.tsx
  src/app/modules/dataset-module/component/datasetSubHeaderToolbar.tsx
  src/app/modules/dataset-upload-module/upload-steps/externalSearch.tsx
  src/app/modules/dataset-upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/home-module/components/All/assetsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/index.tsx
  src/app/modules/home-module/components/Charts/chartsGrid.tsx
  src/app/modules/home-module/components/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/Filter/index.tsx
  src/app/modules/home-module/components/Reports/reportsGrid.tsx
  src/app/modules/home-module/sub-modules/explore-assets/index.tsx
  src/app/modules/home-module/sub-modules/explore-assets/localAssets.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/index.tsx
  src/app/modules/report-module/views/initial/index.tsx
  src/app/state/recoil/atoms/index.ts
Labels: size/L

#190 test: fix cypress tests
  cypress/e2e/1-dx/2-datasets.cy.ts
  cypress/e2e/1-dx/5-dashboard.cy.ts
  src/app/state/recoil/atoms/index.ts
Labels: size/S

#191 feat: DX-1682 - Close Dataxplorer test on Intercom
  public/index.html
  src/app/Routes.tsx
  src/app/components/Dialogs/logOutDialog.tsx
  src/app/modules/user-profile-module/sub-module/settings.tsx
Labels: size/M

#192 fix: Origins should be verified during cross-origin communications
  src/app/hooks/useOneDrivePicker.tsx
Labels: size/XS

#196 feat:DX-1525; new states for AI messaging
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/report-module/components/reportSubHeaderToolbar/styles.ts
Labels: size/M

#200 feat: DX-1601 - Stacked BarChart Implementation, DX-1600 - Multi-set …
  .github/workflows/tests.yml
  src/app/hooks/useDataThemesEchart.tsx
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/components/placeholder/index.tsx
  src/app/modules/chart-module/data.ts
  src/app/modules/chart-module/routes/chart-type/data.tsx
  src/app/modules/chart-module/routes/mapping/error.tsx
  src/app/modules/report-module/components/right-panel-create-view/data.tsx
Labels: size/XL

#198 Feat/dx 1626
  cypress/e2e/1-dx/4-reports.cy.ts
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
Labels: size/L

#197 chore: refactor logic for frames state in RB
  src/app/hooks/useHandleRowFrameItemResize.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/data.ts
  src/app/modules/report-module/__test__/reportRightPanelCreateView.test.tsx
  src/app/modules/report-module/components/right-panel-create-view/index.tsx
  src/app/modules/report-module/components/right-panel/data.ts
  src/app/modules/report-module/components/right-panel/index.tsx
  src/app/modules/report-module/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/addRowFrameButton.tsx
  src/app/modules/report-module/sub-module/rowStructure/index.tsx
  src/app/modules/report-module/sub-module/rowStructure/rowStructureDisplay.tsx
  src/app/modules/report-module/views/create/data.ts
  src/app/modules/report-module/views/create/index.tsx
  src/app/modules/report-module/views/edit/data.ts
  src/app/modules/report-module/views/edit/index.tsx
  src/app/modules/report-module/views/preview/index.tsx
Labels: size/L

#201 Feat/source url
  cypress/e2e/1-dx/2-datasets.cy.ts
  src/app/modules/chart-module/components/common-chart/index.tsx
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/chart-module/util/getDatasetDetailsSource.ts
  src/app/modules/dataset-module/component/datasetSubHeaderToolbar.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/metaData.tsx
  src/app/modules/report-module/components/chart-wrapper/index.tsx
  src/app/utils/emailValidation.ts
Labels: size/L

#202 feat: DX-1486 - show only datasets owned by user
  cypress/e2e/1-dx/3-charts.cy.ts
  cypress/e2e/1-dx/4-reports.cy.ts
  src/app/modules/chart-module/routes/data/index.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/datasetsGrid.tsx
Labels: size/S

#204 fix: Unable to view organisation member chart
  src/app/modules/chart-module/index.tsx
Labels: size/S
