Repository zimmerman-team/Dx.client, pull requests merged in 2025-06, with the labels that each got.

#343 chore: add terms and condition links
  src/app/components/Dialogs/CookieDialog/common/message.tsx
  src/app/modules/chart-module/util/constants/links.ts
  src/app/modules/home-module/components/Footer/DesktopFooter.tsx
  src/app/modules/home-module/components/Footer/MobileFooter.tsx
  src/app/modules/home-module/components/Footer/smallFooter.tsx
Labels: size/M

#344 feat/DX-2521: Implement carousel component and update assets
  src/app/components/AppBar/index.tsx
  src/app/components/AppBar/style.ts
  src/app/components/Styled/button.ts
  src/app/modules/home-module/assets/dashboard-card-a.png
  src/app/modules/home-module/assets/dashboard-card-b.png
  src/app/modules/home-module/assets/dashboard-card-c.png
  src/app/modules/home-module/assets/dashboard-card-d.png
  src/app/modules/home-module/assets/logo.svg
  src/app/modules/home-module/assets/right-arr.svg
  src/app/modules/home-module/components/carousel/carousel.tsx
  src/app/modules/home-module/components/carousel/index.tsx
  src/app/modules/home-module/components/nonAuthUserLibrary/index.tsx
  src/app/modules/home-module/index.tsx
  src/app/modules/home-module/sub-modules/partners/index.tsx
Labels: size/L

#345 Feat/dx 2461
  package.json
  src/app/assets/icons/Redo.tsx
  src/app/assets/icons/Undo.tsx
  src/app/components/ColorPicker/assets/expand-select.tsx
  src/app/components/ColorPicker/assets/reset-icon.tsx
  src/app/components/ColorPicker/components/alpha/index.tsx
  src/app/components/ColorPicker/components/fields/index.tsx
  src/app/components/ColorPicker/components/hue/index.tsx
  src/app/components/ColorPicker/components/interactive/index.tsx
  src/app/components/ColorPicker/components/saturation/index.tsx
  src/app/components/ColorPicker/components/tabs/index.tsx
  src/app/components/ColorPicker/hooks/useBoundingClientRect.ts
  src/app/components/ColorPicker/index.tsx
  src/app/components/ColorPicker/services/color/index.ts
  src/app/components/ColorPicker/styles.ts
  src/app/components/ColorPicker/utils/index.ts
  src/app/modules/chart-module/routes/customize/components/ChartOptionColor.tsx
  src/app/modules/chart-module/routes/customize/components/InlineColorPicker/InlineColorPicker.js
  src/app/modules/chart-module/routes/customize/components/InlineColorPicker/InlineColorPicker.tsx
  src/app/modules/common/RichEditor/BGColorModal/Picker/index.tsx
  src/app/modules/common/RichEditor/BGColorModal/Picker/picker.tsx
  src/app/modules/common/RichEditor/BGColorModal/index.tsx
  src/app/modules/common/RichEditor/ColorModal/Picker/colors.ts
  src/app/modules/common/RichEditor/ColorModal/index.tsx
  src/app/modules/common/RichEditor/button/basicButtons.tsx
  src/app/modules/common/RichEditor/button/indentButtons.tsx
  src/app/modules/common/RichEditor/buttons.tsx
  src/app/modules/common/RichEditor/decorators/colorDecorator.tsx
  src/app/modules/common/RichEditor/decorators/index.tsx
  src/app/modules/common/RichEditor/decorators/linkDecorator.tsx
  src/app/modules/common/RichEditor/decorators/types.ts
  src/app/modules/common/RichEditor/fontSizeHandler/index.tsx
  src/app/modules/common/RichEditor/fontSizeHandler/styleMap.ts
  src/app/modules/common/RichEditor/fontStyleHandler/data.ts
  src/app/modules/common/RichEditor/fontStyleHandler/fontFamilyHandler.tsx
  src/app/modules/common/RichEditor/fontStyleHandler/fontStyleHandler.tsx
  src/app/modules/common/RichEditor/index.tsx
  src/app/modules/common/RichEditor/style/alignmentStyles.module.css
  src/app/modules/common/RichEditor/style/buttonInvertedStyles.module.css
  src/app/modules/common/RichEditor/style/buttonStyles.module.css
  src/app/modules/common/RichEditor/style/editorStyles.module.css
  src/app/modules/common/RichEditor/style/extraButtonStyles.css
  src/app/modules/common/RichEditor/style/indent.css
  src/app/modules/common/RichEditor/style/toolbarInvertedStyles.module.css
  src/app/modules/common/RichEditor/style/toolbarStyles.module.css
  src/app/modules/common/RichEditor/toolbarStyles.module.css
  src/app/modules/story-module/components/right-panel-create-view/index.tsx
  src/app/modules/story-module/components/rowStructure/box.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/staticToolbar.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/styles.ts
  src/app/modules/story-module/index.tsx
  src/app/modules/story-module/views/edit/index.tsx
  src/app/modules/story-module/views/preview/index.tsx
  src/app/utils/getContrastColor.ts
  src/app/utils/hsvtohex.ts
  src/index.css
  src/index.tsx
  yarn.lock
Labels: size/XXL

#339 feat: enhance text editor functionality with dynamic height adjustmen…
  src/app/hooks/useHandleRowFrameItemResize.tsx
  src/app/modules/common/RichEditor/fontSizeHandler/index.tsx
  src/app/modules/common/RichEditor/index.tsx
  src/app/modules/story-module/components/headerBlock/index.tsx
  src/app/modules/story-module/components/placeholder/index.tsx
  src/app/modules/story-module/components/rowStructure/addRowFrameButton.tsx
  src/app/modules/story-module/components/rowStructure/box.tsx
  src/app/modules/story-module/components/rowStructure/data.ts
  src/app/modules/story-module/components/rowStructure/index.tsx
  src/app/modules/story-module/components/rowStructure/rowStructureDisplay.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/index.tsx
  src/app/modules/story-module/data.ts
  src/app/modules/story-module/index.tsx
  src/app/modules/story-module/views/create/data.ts
  src/app/modules/story-module/views/create/index.tsx
  src/app/modules/story-module/views/edit/index.tsx
  src/app/state/recoil/atoms/index.ts
Labels: size/L

#341 feat: DX-2455 - Updated navigation bar
  package.json
  src/app/assets/icons/ChevronUp.tsx
  src/app/components/AppBar/components/drop-down-nav/index.tsx
  src/app/components/AppBar/components/mobile-nav/index.tsx
  src/app/components/AppBar/components/nav-list/index.tsx
  src/app/components/AppBar/index.tsx
  src/app/components/AppBar/style.ts
Labels: size/XL

#346 fix: DX-2477 - Resizing bug for row content
  src/app/modules/story-module/components/rowStructure/box.tsx
  src/app/modules/story-module/components/rowStructure/rowStructureDisplay.tsx
Labels: size/S

#348 updating header styles
  src/app/modules/common/RichEditor/ColorModal/index.tsx
  src/app/modules/common/RichEditor/fontSizeHandler/index.tsx
  src/app/modules/common/RichEditor/fontStyleHandler/data.ts
  src/app/modules/common/RichEditor/fontStyleHandler/style.css
  src/app/modules/common/RichEditor/index.tsx
  src/app/modules/story-module/components/headerBlock/index.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/index.tsx
  src/app/modules/story-module/index.tsx
  src/app/utils/draftjs/createEditorStateWithBlockType.ts
  src/index.css
Labels: size/L

#350 feat: DX-2509 - Sign in page - Check responsiveness and ui accuracy
  src/app/modules/home-module/components/Footer/DesktopFooter.tsx
  src/app/modules/onboarding-module/asset/ellipses.svg
  src/app/modules/onboarding-module/asset/main-image.png
  src/app/modules/onboarding-module/component/card/index.tsx
  src/app/modules/onboarding-module/component/card/style.ts
  src/app/modules/onboarding-module/index.tsx
Labels: size/L

#353 Feat/dx 2472
  public/favicon.ico
  public/favicon.svg
  public/logo192.png
  public/logo512.png
  src/app/modules/common/RichEditor/button/basicButtons.tsx
  src/app/modules/common/RichEditor/button/indentButtons.tsx
  src/app/modules/common/RichEditor/index.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/staticToolbar.tsx
  src/app/modules/story-module/views/initial/data.tsx
  src/app/modules/story-module/views/initial/index.tsx
Labels: size/XL

#354 feat: DX-2540 - Story builder responsiveness
  src/app/modules/story-module/components/headerBlock/index.tsx
  src/app/modules/story-module/components/right-panel/styles.ts
  src/app/modules/story-module/components/rowStructure/addRowFrameButton.tsx
  src/app/modules/story-module/components/rowStructure/box.tsx
  src/app/modules/story-module/components/rowStructure/rowStructureDisplay.tsx
  src/app/modules/story-module/index.tsx
  src/app/modules/story-module/views/edit/index.tsx
Labels: size/M
