Repository zimmerman-team/Dx.client, pull requests merged in 2025-03, with the labels that each got.

#297 feat: enhance story module layout and scrolling behavior
  src/app/modules/story-module/components/placeholder/index.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/styles.ts
  src/app/modules/story-module/index.tsx
  src/app/modules/story-module/views/edit/index.tsx
  src/app/utils/handleAutoScroll.ts
Labels: size/L

#295 fix: review fixes
  src/app/hooks/useOneDrivePicker.tsx
  src/app/modules/common/not-authorized-message/index.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/datasetsGrid.tsx
Labels: size/L

#296 feat: DX-2218 - [Design Rebuilt] Connect data flow
  src/app/modules/dataset-module/routes/upload-module/component/stepper.tsx
  src/app/modules/dataset-module/routes/upload-module/component/table/externalSearchTable/index.tsx
  src/app/modules/dataset-module/routes/upload-module/style.ts
  src/app/modules/dataset-module/routes/upload-module/upload-steps/externalSearch.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/index.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/metaData.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/processing.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/externalDatasetCard.tsx
Labels: size/L

#294 feat: DX-2271 - Logic implementation Asset Owner on Card
  src/app/modules/dataset-module/data.ts
  src/app/modules/home-module/__test__/chartCard.test.tsx
  src/app/modules/home-module/__test__/reportCard.test.tsx
  src/app/modules/home-module/components/AssetCollection/All/assetsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Charts/chartsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Charts/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/Stories/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/Stories/storiesGrid.tsx
  src/app/modules/story-module/data.ts
Labels: size/S

#298 feat: DX-2286 - [1-1 implementation review - S41] dashboard (signed in)
  src/app/assets/icons/AIIcon.tsx
  src/app/components/Styled/tabs.ts
  src/app/modules/home-module/assets/table-icon.svg
  src/app/modules/home-module/components/AssetCollection/Charts/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/datasetCategoryList.tsx
  src/app/modules/home-module/components/AssetCollection/index.tsx
  src/app/modules/home-module/components/Filter/index.tsx
Labels: size/M

#299 feat: DX-2289 - [1-1 implementation review - S41] footer
  cypress/e2e/1-test-login.cy.ts
  cypress/e2e/4-reports.cy.ts
  src/app/components/Dialogs/TourGuide/rowFrameIntro.tsx
  src/app/modules/callback-module/index.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/chart-module/routes/customize/index.tsx
  src/app/modules/chart-module/routes/filters/index.tsx
  src/app/modules/chart-module/routes/mapping/index.tsx
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/chart-module/routes/preview/index.tsx
  src/app/modules/chart-module/routes/select-data/index.tsx
  src/app/modules/dataset-module/routes/datasetDetail/index.tsx
  src/app/modules/dataset-module/routes/edit/index.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/index.tsx
  src/app/modules/home-module/components/Footer/DesktopFooter.tsx
  src/app/modules/home-module/components/nonAuthUserLibrary/infoCard.tsx
  src/app/modules/home-module/components/nonAuthUserLibrary/signupDialog.tsx
  src/app/modules/home-module/index.tsx
  src/app/modules/home-module/sub-modules/about/index.tsx
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/home-module/sub-modules/dashboard/index.tsx
  src/app/modules/home-module/sub-modules/landing/index.tsx
  src/app/modules/home-module/sub-modules/partners/index.tsx
  src/app/modules/home-module/sub-modules/pricing/index.tsx
  src/app/modules/home-module/sub-modules/why-dx/index.tsx
  src/app/modules/onboarding-module/component/card/index.tsx
  src/app/modules/onboarding-module/index.tsx
  src/app/modules/story-module/views/ai-template/index.tsx
  src/app/modules/story-module/views/create/index.tsx
  src/app/modules/story-module/views/edit/index.tsx
  src/app/modules/story-module/views/initial/index.tsx
  src/app/modules/story-module/views/preview/index.tsx
  src/app/modules/user-profile-module/index.tsx
  src/app/modules/user-profile-module/sub-module/profile.tsx
Labels: size/M

#300 feat: DX-2222 - [Design Rebuilt] Chart - RHCP
  src/app/assets/icons/data-themes-chart-types/multisetBarChart.tsx
  src/app/assets/icons/data-themes-chart-types/stackedBarChart.tsx
  src/app/modules/chart-module/assets/areastackedPreview.svg
  src/app/modules/chart-module/assets/barChartPreview.svg
  src/app/modules/chart-module/assets/bigNumberPreview.svg
  src/app/modules/chart-module/assets/bubbleChartPreview.svg
  src/app/modules/chart-module/assets/circlepackingPreview.svg
  src/app/modules/chart-module/assets/circulargraphPreview.svg
  src/app/modules/chart-module/assets/dateIcon.svg
  src/app/modules/chart-module/assets/forcegraphPreview.svg
  src/app/modules/chart-module/assets/geomapPreview.svg
  src/app/modules/chart-module/assets/graphglPreview.svg
  src/app/modules/chart-module/assets/heatmapPreview.svg
  src/app/modules/chart-module/assets/lineChartPreview.svg
  src/app/modules/chart-module/assets/multisetBarChartPreview.svg
  src/app/modules/chart-module/assets/numberIcon.svg
  src/app/modules/chart-module/assets/pieChartPreview.svg
  src/app/modules/chart-module/assets/radarChartPreview.svg
  src/app/modules/chart-module/assets/sankeyPreview.svg
  src/app/modules/chart-module/assets/scatterChartPreview.svg
  src/app/modules/chart-module/assets/stackedBarChartPreview.svg
  src/app/modules/chart-module/assets/stringIcon.svg
  src/app/modules/chart-module/assets/sunburstPreview.svg
  src/app/modules/chart-module/assets/treemapPreview.svg
  src/app/modules/chart-module/components/chartSubheaderToolbar/styles.ts
  src/app/modules/chart-module/components/toolbox/steps/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/navbar/style.ts
  src/app/modules/chart-module/components/toolbox/steps/panels-content/ChartType.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/Mapping.tsx
  src/app/modules/chart-module/components/toolbox/steps/sub-header.tsx
  src/app/modules/chart-module/components/toolbox/styles.tsx
  src/app/modules/chart-module/routes/chart-type/data.tsx
  src/app/modules/chart-module/routes/chart-type/index.tsx
  src/app/modules/chart-module/routes/filters/components/ExpandedFilterGroup.tsx
Labels: size/XXL

#312 Fix/implementation reviews
  src/app/hooks/useTogglePanelWithKey.ts
  src/app/modules/chart-module/components/toolbox/index.tsx
  src/app/modules/home-module/components/AddAssetDropdown/index.tsx
  src/app/modules/home-module/components/AssetCollection/Charts/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/Stories/gridItem.tsx
  src/app/modules/story-module/components/right-panel/data.ts
  src/app/modules/story-module/components/right-panel/index.tsx
  src/app/modules/story-module/index.tsx
Labels: size/M

#301 feat: DX-2276 - [1-1 implementation review - S41] pricing page card b…
  src/app/hooks/useCheckPricingActive.tsx
  src/app/modules/home-module/sub-modules/pricing/components/mobile-plan-card.tsx
  src/app/modules/home-module/sub-modules/pricing/components/plan-card.tsx
  src/app/modules/home-module/sub-modules/pricing/index.tsx
Labels: size/L

#302 feat: DX-2283 - [1-1 implementation review - S41] Why Dataxplorer
  src/app/modules/home-module/assets/hero-ellipses-mobile.svg
  src/app/modules/home-module/assets/hero-ellipses-tablet.svg
  src/app/modules/home-module/assets/hero-ellipses.png
  src/app/modules/home-module/assets/hero-ellipses.svg
  src/app/modules/home-module/components/hero/index.tsx
  src/app/modules/home-module/sub-modules/about/index.tsx
  src/app/modules/home-module/sub-modules/why-dx/components/tryUsBlock.tsx
  src/app/modules/home-module/sub-modules/why-dx/index.tsx
  src/app/modules/home-module/sub-modules/why-dx/style.ts
Labels: size/L

#303 feat: DX-2224 - [Design Rebuilt] Story Preview
  src/app/modules/story-module/components/chart-wrapper/index.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/styles.ts
Labels: size/XS

#306 feat: DX-2293 - [1-1 implementation review - S41] Pricing page
  src/app/modules/home-module/sub-modules/pricing/components/features.tsx
Labels: size/XS

#307 feat: DX-2291 - [1-1 implementation review - S41] About
  src/app/modules/home-module/assets/back-arrow.svg
  src/app/modules/home-module/sub-modules/about/index.tsx
  src/app/modules/home-module/sub-modules/about/style.ts
Labels: size/L

#308 feat: DX-2292 - [1-1 implementation review - S41] Partners
  src/app/modules/home-module/sub-modules/partners/components/quoteBlock.tsx
  src/app/modules/home-module/sub-modules/partners/components/tabCard.tsx
  src/app/modules/home-module/sub-modules/partners/index.tsx
  src/app/modules/home-module/sub-modules/partners/style.ts
Labels: size/S

#309 feat: DX-2294 - [1-1 implementation review - S41] Contact
  src/app/modules/home-module/sub-modules/contact/index.tsx
Labels: size/XS

#310 feat: DX-2295 - [1-1 implementation review - S41] Dataset preview page
  src/app/modules/dataset-module/routes/upload-module/style.ts
  src/app/modules/dataset-module/routes/upload-module/upload-steps/finishedFragment.tsx
Labels: size/M

#305 feat: DX-2298 - [1-1 implementation review - S41] User profile
  src/app/modules/user-profile-module/style.ts
  src/app/modules/user-profile-module/sub-module/profile.tsx
Labels: size/L

#319 feat: DX-2302 - [1-1 Implementation Review - Platform] About
  src/app/modules/home-module/sub-modules/about/index.tsx
Labels: size/L

#315 fix: upload progress hooks to improve time estimation and formatting
  src/app/hooks/useOnUploadProgress.ts
  src/app/modules/dataset-module/routes/upload-module/upload-steps/index.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/processing.tsx
Labels: size/L

#320 feat: DX-2301 - [1-1 Implementation Review - Platform] Why Dataxplorer
  src/app/modules/home-module/sub-modules/why-dx/components/keyFeaturesBlock.tsx
  src/app/modules/home-module/sub-modules/why-dx/components/tryUsBlock.tsx
  src/app/modules/home-module/sub-modules/why-dx/index.tsx
  src/app/modules/home-module/sub-modules/why-dx/style.ts
Labels: size/M

#316 fix:Add validator library and improve URL handling in dataset details
  package.json
  src/app/modules/chart-module/util/getDatasetDetailsSource.ts
  src/app/modules/dataset-module/routes/upload-module/upload-steps/finishedFragment.tsx
  src/app/utils/emailValidation.ts
  yarn.lock
Labels: size/M

#304 feat: DX-2290 - [1-1 implementation review - S41] Downloaded PDF logo…
  package.json
  src/app/modules/story-module/components/chart-wrapper/useRenderChartFromAPI.ts
  src/app/modules/user-profile-module/component/table.tsx
  src/app/utils/exportPage.ts
  yarn.lock
Labels: size/L

#318 feat: DX-2300 - [1-1 Implementation Review - Platform] Homepage/Dashb
  src/app/modules/home-module/components/AssetCollection/index.tsx
  src/app/modules/home-module/components/nonAuthUserLibrary/index.tsx
  src/app/modules/home-module/index.tsx
Labels: size/XS

#321 fix: hide and show app bar in DownloadedView component
  src/app/modules/story-module/views/downloaded-view/index.tsx
  yarn.lock
Labels: size/S

#313 Feat/dx 2267
  src/app/Routes.tsx
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/data.ts
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/util/getDatasetDetailsSource.ts
  src/app/modules/common/not-available/asset/smile.svg
  src/app/modules/common/not-available/index.tsx
  src/app/modules/dataset-module/component/datasetSubHeaderToolbar.tsx
  src/app/modules/dataset-module/index.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/gridItem.tsx
  src/app/modules/home-module/components/Table/index.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/index.tsx
  src/app/modules/story-module/index.tsx
  src/app/modules/user-profile-module/style.ts
  src/app/modules/user-profile-module/sub-module/billing.tsx
  src/app/modules/user-profile-module/sub-module/profile.tsx
  src/app/state/recoil/atoms/index.ts
  src/app/theme/index.ts
  src/app/utils/AuthProtectedRoute.tsx
Labels: size/XXL

#322 feat: DX-2304 - [1-1 Implementation Review - Platform] Partners
  src/app/modules/home-module/sub-modules/partners/components/tabCard.tsx
  src/app/modules/home-module/sub-modules/partners/index.tsx
Labels: size/S

#324 feat: DX-2310 - [1-1 Implementation Review - Platform] Create story
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/story-module/components/headerBlock/index.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/index.tsx
Labels: size/L
