Repository zimmerman-team/Dx.client, pull requests merged in 2025-07, with the labels that each got.

#357 Feat/gen updates
  .github/workflows/lint.yml
  .stylelintrc
  GruntFile.js
  craco.config.js
  cypress/e2e/8-footer.cy.ts
  package.json
  public/astra-46d96db2-a64d-45dc-9710-9dd6ef7878b1.html
  public/manifest.json
  public/static/simple.geo.json
  src/app/components/Dialogs/CookieDialog/common/message.tsx
  src/app/hooks/useDataThemesEchart.tsx
  src/app/hooks/useEditorPlugins.tsx
  src/app/modules/chart-module/routes/customize/data.ts
  src/app/modules/chart-module/util/constants/index.ts
  src/app/modules/common/RichEditor/anchor/components/AddLinkForm.tsx
  src/app/modules/common/RichEditor/anchor/components/DefaultLinkButton.tsx
  src/app/modules/common/RichEditor/anchor/components/Link.tsx
  src/app/modules/common/RichEditor/anchor/components/LinkButton.tsx
  src/app/modules/common/RichEditor/anchor/index.tsx
  src/app/modules/common/RichEditor/anchor/linkStrategy.ts
  src/app/modules/common/RichEditor/anchor/theme.ts
  src/app/modules/common/RichEditor/anchor/utils/EditorUtils.ts
  src/app/modules/common/RichEditor/anchor/utils/URLUtils.ts
  src/app/modules/common/RichEditor/anchor/utils/mailRegex.ts
  src/app/modules/common/RichEditor/anchor/utils/urlRegex.ts
  src/app/modules/common/RichEditor/button/indentButtons.tsx
  src/app/modules/common/RichEditor/button/linkButton.tsx
  src/app/modules/common/RichEditor/fontSizeHandler/index.tsx
  src/app/modules/common/RichEditor/fontStyleHandler/fontFamilyHandler.tsx
  src/app/modules/common/RichEditor/fontStyleHandler/fontStyleHandler.tsx
  src/app/modules/common/RichEditor/index.tsx
  src/app/modules/common/RichEditor/style/editorStyles.module.css
  src/app/modules/home-module/components/AssetCollection/Stories/gridItem.tsx
  src/app/modules/home-module/components/Footer/DesktopFooter.tsx
  src/app/modules/home-module/components/Footer/MobileFooter.tsx
  src/app/modules/home-module/components/Footer/smallFooter.tsx
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/home-module/sub-modules/pricing/components/plan-card.tsx
  src/app/modules/home-module/sub-modules/pricing/index.tsx
  src/app/modules/story-module/__test__/headerBlock.test.tsx
  src/app/modules/story-module/components/headerBlock/index.tsx
  src/app/modules/story-module/components/placeholder/index.tsx
  src/app/modules/story-module/components/right-panel-create-view/index.tsx
  src/app/modules/story-module/components/rowStructure/addRowFrameButton.tsx
  src/app/modules/story-module/components/rowStructure/box.tsx
  src/app/modules/story-module/components/rowStructure/index.tsx
  src/app/modules/story-module/components/rowStructure/rowStructureDisplay.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/index.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/staticToolbar.tsx
  src/app/modules/story-module/index.tsx
  src/app/modules/story-module/views/create/data.ts
  src/app/modules/story-module/views/create/index.tsx
  src/app/modules/story-module/views/edit/data.ts
  src/app/modules/story-module/views/edit/index.tsx
  src/app/modules/story-module/views/preview/index.tsx
  src/app/utils/draftjs/copyPaste.ts
  src/app/utils/draftjs/getEntityKey.ts
  src/index.css
  src/setupTests.js
  yarn.lock
Labels: size/XXL

#359 feat: DX-2607 - Line chart mapping should be similar to that of the s…
  src/app/hooks/useDataThemesEchart.tsx
Labels: size/M

#360 feat: DX-2609 - Add pie chart labels
  src/app/hooks/useDataThemesEchart.tsx
Labels: size/S

#361 chore: updates
  src/app/hooks/useDataThemesEchart.tsx
Labels: size/XS
