Repository zimmerman-team/Dx.client, pull requests merged in 2025-02, with the labels that each got.

#285 Test/cypress partial
  .github/workflows/tests.yml
  .gitignore
  cypress/e2e/1-test-login.cy.ts
  cypress/e2e/10-contact.cy.ts
  cypress/e2e/11-user-profile.cy.ts
  cypress/e2e/12-test-logout.cy.ts
  cypress/e2e/13-partners.cy.ts
  cypress/e2e/2-datasets.cy.ts
  cypress/e2e/3-charts.cy.ts
  cypress/e2e/4-reports.cy.ts
  cypress/e2e/5-dashboard.cy.ts
  cypress/e2e/6-home.cy.ts
  cypress/e2e/8-footer.cy.ts
  cypress/e2e/9-header.cy.ts
  cypress/e2e/pages/partners.cy.ts
  cypress/e2e/pages/pricing.cy.ts
  cypress/e2e/pages/why-dataxplorer.cy.ts
  cypress/support/commands.ts
  package.json
  public/static/dataset-detail 2.webp
  src/app/components/AppBar/index.tsx
  src/app/components/Dialogs/logOutDialog.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/Mapping.tsx
  src/app/modules/chart-module/components/toolbox/steps/sub-header.tsx
  src/app/modules/chart-module/routes/customize/components/ChartOptionColor.js
  src/app/modules/chart-module/routes/customize/components/InlineColorPicker/InlineColorPicker.js
  src/app/modules/chart-module/routes/filters/components/ExpandedFilterGroup.tsx
  src/app/modules/chart-module/routes/filters/components/FilterGroup.tsx
  src/app/modules/home-module/components/AssetCollection/index.tsx
  src/app/modules/home-module/components/Footer/DesktopFooter.tsx
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/home-module/sub-modules/partners/components/empowerBlock.tsx
  src/app/modules/home-module/sub-modules/partners/index.tsx
  src/app/modules/home-module/sub-modules/pricing/components/plan-card.tsx
  src/app/modules/story-module/components/headerBlock/index.tsx
  src/app/modules/story-module/components/placeholder/index.tsx
  src/app/modules/story-module/components/right-panel-create-view/index.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/exportButton.tsx
  src/app/modules/user-profile-module/component/tab.tsx
  src/app/modules/user-profile-module/component/table.tsx
  src/app/modules/user-profile-module/layout.tsx
  yarn.lock
Labels: size/XXL

#289 feat: add keyboard toggle for toolbox panel with tooltip instruction
  src/app/modules/chart-module/components/toolbox/data.tsx
  src/app/modules/chart-module/components/toolbox/index.tsx
  src/app/modules/chart-module/index.tsx
Labels: size/L

#284 feat: add tooltips to filter icons and update tooltip background color
  src/app/modules/home-module/components/Filter/index.tsx
  src/app/theme/index.ts
Labels: size/S

#286 feat: add tooltip for upload option button
  src/app/modules/dataset-module/routes/upload-module/component/uploadOption.tsx
Labels: size/L

#288 Feat/dx 2207/dx 2204
  src/app/components/AppBar/index.tsx
  src/app/components/AppBar/style.ts
  src/app/components/Dialogs/CookieDialog/common/message.tsx
  src/app/components/Dialogs/CookieDialog/index.tsx
  src/app/components/Dialogs/EmbedChartDialog/copyButton.tsx
  src/app/components/Dialogs/EmbedChartDialog/embedOptions.tsx
  src/app/components/Dialogs/EmbedChartDialog/linkOptions.tsx
  src/app/components/Dialogs/PlanDialog/common/message.tsx
  src/app/components/Dialogs/PlanDialog/index.tsx
  src/app/components/Dialogs/deleteAccountDialog.tsx
  src/app/components/Dialogs/deleteChartDialog.tsx
  src/app/components/Dialogs/deleteDatasetDialog.tsx
  src/app/components/Dialogs/deleteStoryDialog.tsx
  src/app/components/Dialogs/logOutDialog.tsx
  src/app/components/Styled/button.ts
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/components/toolbox/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/index.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/SelectDataset.tsx
  src/app/modules/chart-module/components/toolbox/styles.tsx
  src/app/modules/chart-module/routes/filters/components/ExpandedFilterGroup.tsx
  src/app/modules/dataset-module/component/datasetSubHeaderToolbar.tsx
  src/app/modules/dataset-module/routes/upload-module/component/externalSourcesList.tsx
  src/app/modules/dataset-module/routes/upload-module/component/uploadOption.tsx
  src/app/modules/dataset-module/routes/upload-module/style.ts
  src/app/modules/dataset-module/routes/upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/metaData.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/previewFragment.tsx
  src/app/modules/home-module/components/AddAssetDropdown/index.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/datasetCategoryList.tsx
  src/app/modules/home-module/components/AssetCollection/index.tsx
  src/app/modules/home-module/components/hero/index.tsx
  src/app/modules/home-module/style.ts
  src/app/modules/home-module/sub-modules/about/index.tsx
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/home-module/sub-modules/partners/components/bestDecisionBlock.tsx
  src/app/modules/home-module/sub-modules/partners/components/empowerBlock.tsx
  src/app/modules/home-module/sub-modules/partners/style.ts
  src/app/modules/home-module/sub-modules/pricing/components/plan-card.tsx
  src/app/modules/home-module/sub-modules/why-dx/components/tryUsBlock.tsx
  src/app/modules/story-module/asset/redo-icon.svg
  src/app/modules/story-module/components/right-panel-create-view/index.tsx
  src/app/modules/story-module/components/right-panel-create-view/rhpGridItem.tsx
  src/app/modules/story-module/components/right-panel/styles.ts
  src/app/modules/story-module/components/rowStructure/addRowFrameButton.tsx
  src/app/modules/story-module/components/rowStructure/data.ts
  src/app/modules/story-module/components/rowStructure/index.tsx
  src/app/modules/story-module/components/rowStructure/rowStructureDisplay.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/index.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/infosnackbar.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/staticToolbar.tsx
  src/app/modules/story-module/views/create/index.tsx
  src/app/modules/story-module/views/edit/index.tsx
  src/app/modules/story-module/views/initial/data.tsx
  src/app/modules/story-module/views/preview/index.tsx
  src/app/modules/user-profile-module/component/table.tsx
  src/app/modules/user-profile-module/style.ts
  src/app/modules/user-profile-module/sub-module/billing.tsx
  src/app/modules/user-profile-module/sub-module/settings.tsx
Labels: size/XXL

#292 Feat/design rebuilt
  src/app/components/Dialogs/deleteChartDialog.tsx
  src/app/components/ErrorBoundary/index.tsx
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/home-module/components/AssetCollection/Charts/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/Stories/gridItem.tsx
  src/app/modules/home-module/components/hero/index.tsx
  src/app/modules/home-module/sub-modules/about/index.tsx
  src/app/modules/home-module/sub-modules/about/style.ts
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/home-module/sub-modules/pricing/index.tsx
  src/app/modules/story-module/components/headerBlock/index.tsx
  src/app/modules/story-module/components/rowStructure/rowStructureDisplay.tsx
  src/app/modules/user-profile-module/sub-module/settings-hook.tsx
Labels: size/XL

#291 feat: DX-2185 - Add Logo on Downloaded PDF version
  src/app/modules/story-module/views/downloaded-view/index.tsx
  src/app/modules/story-module/views/preview/index.tsx
Labels: size/M

#293 feat: DX-2270 - Logic Implementation Filter My Assets
  src/app/modules/home-module/components/AssetCollection/All/assetsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Charts/chartsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Stories/storiesGrid.tsx
  src/app/modules/home-module/components/AssetCollection/index.tsx
Labels: size/M
