Repository zimmerman-team/Dx.client, pull requests merged in 2025-01, with the labels that each got.

#279 fix: DX-2127 - Infite scroll doesn't always work for dataset table
  src/app/components/Table/Preview-table/index.tsx
  src/app/hooks/useInfinityScroll.ts
  src/app/modules/dataset-module/routes/upload-module/component/table/data-table/index.tsx
Labels: size/S

#270 DX-2022 | Lighthouse report based fixes
  public/index.html
  public/static/dataset-detail.webp
  public/static/fundportfoliomanager.png
  src/app/modules/common/newsletterForm/index.tsx
  src/app/modules/home-module/components/Filter/index.tsx
  src/app/modules/home-module/index.tsx
  src/app/modules/home-module/style.ts
  src/react-app-env.d.ts
Labels: size/M

#281 DX-2013 | Payment flow
  public/index.html
  src/app/Routes.tsx
  src/app/hooks/useChartsRawData.tsx
  src/app/hooks/useCheckUserPlan.tsx
  src/app/hooks/useGetChartsStoriesCountByDataset.tsx
  src/app/hooks/useGetDatasetContent.tsx
  src/app/hooks/useSearchMediaSources.tsx
  src/app/modules/callback-module/index.tsx
  src/app/modules/callback-module/payment.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/common/newsletterForm/index.tsx
  src/app/modules/dataset-module/routes/edit/index.tsx
  src/app/modules/dataset-module/routes/upload-module/component/dropzone/index.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/index.tsx
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/home-module/sub-modules/pricing/index.tsx
  src/app/modules/story-module/components/chart-wrapper/useLoadDatasetDetailsAPI.tsx
  src/app/modules/story-module/components/chart-wrapper/useRenderChartFromAPI.ts
  src/app/modules/user-profile-module/component/table.tsx
  src/app/modules/user-profile-module/style.ts
  src/app/modules/user-profile-module/sub-module/billing.tsx
  src/app/modules/user-profile-module/sub-module/settings.tsx
  src/app/state/api/index.ts
Labels: size/XL

#282 feat: DX-1823 - Implement the new state colour for current plan
  src/app/modules/home-module/sub-modules/pricing/components/mobile-plan-card.tsx
  src/app/modules/home-module/sub-modules/pricing/components/plan-card.tsx
Labels: size/XS
