Repository zimmerman-team/Dx.client, pull requests merged in 2025-05, with the labels that each got.

#326 style: update responsive breakpoints and improve layout styles
  src/app/modules/chart-module/components/chartSubheaderToolbar/index.tsx
  src/app/modules/chart-module/index.tsx
  src/app/modules/chart-module/routes/preview-theme/index.tsx
  src/app/modules/common/RichEditor/toolbarStyles.module.css
  src/app/modules/dataset-module/component/datasetSubHeaderToolbar.tsx
  src/app/modules/dataset-module/component/styles.ts
  src/app/modules/dataset-module/routes/upload-module/style.ts
  src/app/modules/dataset-module/routes/upload-module/upload-steps/finishedFragment.tsx
  src/app/modules/home-module/components/AddAssetDropdown/index.tsx
  src/app/modules/home-module/components/AssetCollection/Charts/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/menuItems.tsx
  src/app/modules/home-module/components/AssetCollection/Stories/gridItem.tsx
  src/app/modules/home-module/components/AssetCollection/index.tsx
  src/app/modules/home-module/components/hero/index.tsx
  src/app/modules/home-module/sub-modules/about/index.tsx
  src/app/modules/home-module/sub-modules/about/style.ts
  src/app/modules/home-module/sub-modules/partners/index.tsx
  src/app/modules/home-module/sub-modules/pricing/index.tsx
  src/app/modules/home-module/sub-modules/why-dx/components/keyFeaturesBlock.tsx
  src/app/modules/home-module/sub-modules/why-dx/components/tryUsBlock.tsx
  src/app/modules/home-module/sub-modules/why-dx/style.ts
  src/app/modules/story-module/components/right-panel-create-view/index.tsx
  src/app/modules/story-module/components/right-panel-create-view/rhpGridItem.tsx
  src/app/modules/story-module/components/right-panel/index.tsx
  src/app/modules/story-module/components/right-panel/styles.ts
  src/app/modules/story-module/components/rowStructure/addRowFrameButton.tsx
  src/app/modules/story-module/components/rowStructure/rowStructureDisplay.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/index.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/infosnackbar.tsx
  src/app/modules/story-module/components/storySubHeaderToolbar/styles.ts
  src/app/modules/story-module/views/edit/index.tsx
  src/app/theme/index.ts
Labels: size/XL

#240 chore: update pre-commit prettier to only check changed files
  .husky/pre-commit
Labels: size/S

#334 feat: DX-2399 - When you adjust the size of the section, the boxes in…
  src/app/hooks/useHandleRowFrameItemResize.tsx
  src/app/modules/story-module/components/rowStructure/rowStructureDisplay.tsx
Labels: size/L

#332 Feat/dx 2441
  public/logo.svg
  src/app/components/AppBar/index.tsx
  src/app/components/AppBar/style.ts
  src/app/modules/common/newsletterForm/index.tsx
  src/app/modules/home-module/assets/gf-logo.png
  src/app/modules/home-module/assets/gf-logo.svg
  src/app/modules/home-module/assets/iati-logo.png
  src/app/modules/home-module/assets/inline-logo.tsx
  src/app/modules/home-module/assets/mfa-finland-logo.png
  src/app/modules/home-module/assets/mfa-finland-logo.svg
  src/app/modules/home-module/components/Footer/DesktopFooter.tsx
  src/app/modules/home-module/components/Footer/asset/logo.svg
  src/app/modules/home-module/components/Footer/index.tsx
  src/app/modules/home-module/components/SignInButtons/assets/google-icon.svg
  src/app/modules/home-module/components/SignInButtons/assets/linkedin-icon.svg
  src/app/modules/home-module/components/SignInButtons/assets/microsoft-icon.svg
  src/app/modules/home-module/components/SignInButtons/index.tsx
  src/app/modules/home-module/components/TryUsBlock/index.tsx
  src/app/modules/home-module/components/hero/index.tsx
  src/app/modules/home-module/index.tsx
  src/app/modules/home-module/sub-modules/about/index.tsx
  src/app/modules/home-module/sub-modules/contact/assets/success-icon.svg
  src/app/modules/home-module/sub-modules/contact/components/input/index.tsx
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/home-module/sub-modules/partners/assets/inline-gf-logo.svg
  src/app/modules/home-module/sub-modules/partners/components/ourPartnersBlock.tsx
  src/app/modules/home-module/sub-modules/partners/components/quoteBlock.tsx
  src/app/modules/home-module/sub-modules/partners/components/tabCard.tsx
  src/app/modules/home-module/sub-modules/partners/components/useDXBlock.tsx
  src/app/modules/home-module/sub-modules/partners/index.tsx
  src/app/modules/home-module/sub-modules/partners/style.ts
  src/app/modules/home-module/sub-modules/why-dx/components/tryUsBlock.tsx
  src/app/modules/home-module/sub-modules/why-dx/index.tsx
  src/app/modules/home-module/sub-modules/why-dx/style.ts
Labels: size/XXL

#335 Feat/dx 2413/dx18
  src/app/hooks/useDataThemesEchart.tsx
  src/app/hooks/useHandleRowFrameItemResize.tsx
  src/app/modules/chart-module/components/toolbox/steps/panels-content/Customize.tsx
  src/app/modules/common/RichEditor/FontSizeController/index.tsx
  src/app/modules/common/RichEditor/index.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/externalSearch.tsx
  src/app/modules/story-module/components/headerBlock/index.tsx
  src/app/modules/story-module/components/headerBlock/style.ts
  src/app/modules/story-module/components/right-panel-create-view/index.tsx
  src/app/modules/story-module/components/rowStructure/box.tsx
  src/app/modules/story-module/components/rowStructure/index.tsx
  src/app/modules/story-module/components/rowStructure/rowStructureDisplay.tsx
  src/app/modules/story-module/data.ts
  src/app/utils/draftjs/getComplexSelectionLength.ts
Labels: size/XXL

#338 Fix/review report fixes
  src/app/modules/common/RichEditor/FontSizeController/index.tsx
  src/app/modules/story-module/components/headerBlock/index.tsx
  src/app/modules/story-module/components/rowStructure/box.tsx
  src/app/modules/story-module/components/rowStructure/rowStructureDisplay.tsx
  src/app/modules/story-module/data.ts
Labels: size/L
