Repository zimmerman-team/Dx.client, pull requests merged in 2025-08, with the labels that each got.

#364 feat: paginate-charts-on-report-builder
  .github/workflows/tests.yml
  cypress/e2e/01-test-login.cy.ts
  cypress/e2e/02-datasets.cy.ts
  cypress/e2e/03-charts.cy.ts
  cypress/e2e/04-reports.cy.ts
  cypress/e2e/05-dashboard.cy.ts
  cypress/e2e/06-home.cy.ts
  cypress/e2e/07-general.cy.ts
  cypress/e2e/08-footer.cy.ts
  cypress/e2e/09-header.cy.ts
  cypress/e2e/10-contact.cy.ts
  cypress/e2e/11-user-profile.cy.ts
  cypress/e2e/13-partners.cy.ts
  cypress/e2e/pages/partners.cy.ts
  cypress/e2e/pages/pricing.cy.ts
  cypress/e2e/pages/why-dataxplorer.cy.ts
  src/app/components/AppBar/components/nav-list/index.tsx
  src/app/modules/home-module/components/Footer/DesktopFooter.tsx
  src/app/modules/home-module/sub-modules/contact/index.tsx
  src/app/modules/story-module/components/right-panel-create-view/index.tsx
Labels: size/XL

#367 fix: update dashboard card image asset
  src/app/modules/home-module/assets/dashboard-card-d.png
Labels: size/XS

#370 Fix/dx 2646
  src/app/modules/common/RichEditor/ColorModal/index.tsx
  src/app/modules/common/RichEditor/fontStyleHandler/data.ts
  src/app/modules/common/RichEditor/fontStyleHandler/fontStyleHandler.tsx
  src/app/modules/common/RichEditor/index.tsx
  src/app/modules/story-module/components/rowStructure/box.tsx
  src/app/utils/draftjs/getStyleEl.ts
  src/app/utils/draftjs/setBlockData.ts
Labels: size/L

#371 feat: DX-2610 - Show baseline assets when logged in.
  src/app/modules/chart-module/routes/select-data/index.tsx
  src/app/modules/home-module/components/AssetCollection/All/assetsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Charts/chartsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Datasets/datasetsGrid.tsx
  src/app/modules/home-module/components/AssetCollection/Stories/storiesGrid.tsx
  src/app/modules/home-module/components/AssetCollection/index.tsx
  src/app/modules/home-module/components/Filter/index.tsx
  src/app/state/recoil/atoms/index.ts
Labels: size/M
