Repository zimmerman-team/Dx.client, pull requests merged in 2025-04, with the labels that each got.

#325 test: run cypress on self-hosted
  .github/workflows/tests.yml
Labels: size/L

#328 feat:DX-2392; implement upgrade flow with Stripe return handling
  src/app/Routes.tsx
  src/app/components/Dialogs/PlanDialog/common/message.tsx
  src/app/modules/home-module/sub-modules/pricing/index.tsx
  src/app/modules/user-profile-module/sub-module/billing.tsx
Labels: size/M

#329 fix:DX-2394;DX-2393; remove SearchLayout component and update chart a…
  src/app/components/Search/layout.tsx
  src/app/modules/chart-module/components/chart-area/index.tsx
  src/app/state/recoil/atoms/index.ts
Labels: size/L

#327 feat:DX-2391; add Enter key support for newsletter and external searc…
  src/app/modules/common/newsletterForm/index.tsx
  src/app/modules/dataset-module/routes/upload-module/upload-steps/externalSearch.tsx
Labels: size/S
